export interface EnadeQuestion {
  id: string;
  topic: string;
  subtopic: string;
  difficulty: 'fácil' | 'médio' | 'difícil';
  year?: number;
  enadeId?: string;
  statement: string;
  alternatives: { letter: string; text: string }[];
  correctAnswer: string;
  explanation: string;
}

export const enadeQuestions: EnadeQuestion[] = [
  // === Algoritmos e Estruturas de Dados (7 questions) ===
  {
    id: 'aed-1',
    topic: 'Algoritmos e Estruturas de Dados',
    subtopic: 'Ordenação',
    difficulty: 'fácil',
    year: 2021,
    statement: 'Um programador precisa ordenar um array de 10.000 números inteiros. Considere os algoritmos de ordenação Bubble Sort, Insertion Sort e Merge Sort. Analisando a complexidade de tempo de cada algoritmo no pior caso, qual é a afirmativa correta?',
    alternatives: [
      { letter: 'A', text: 'O Bubble Sort possui complexidade O(n log n) no pior caso, sendo mais eficiente que o Insertion Sort.' },
      { letter: 'B', text: 'O Insertion Sort possui complexidade O(n²) no pior caso, assim como o Bubble Sort, enquanto o Merge Sort possui O(n log n).' },
      { letter: 'C', text: 'O Merge Sort possui complexidade O(n²) no pior caso, mas é mais eficiente na prática devido ao seu comportamento de cache.' },
      { letter: 'D', text: 'Todos os três algoritmos possuem a mesma complexidade O(n²) no pior caso, diferindo apenas na implementação.' },
      { letter: 'E', text: 'O Bubble Sort é sempre mais eficiente que o Insertion Sort, pois realiza menos comparações no pior caso.' },
    ],
    correctAnswer: 'B',
    explanation: 'O Bubble Sort e o Insertion Sort possuem complexidade O(n²) no pior caso. O Merge Sort, sendo um algoritmo de divisão e conquista, possui complexidade O(n log n) no pior caso, tornando-o significativamente mais eficiente para grandes conjuntos de dados.',
  },
  {
    id: 'aed-2',
    topic: 'Algoritmos e Estruturas de Dados',
    subtopic: 'Árvores',
    difficulty: 'médio',
    year: 2018,
    statement: 'Em uma árvore binária de busca (BST) com nós contendo valores inteiros, são inseridos na seguinte ordem: 50, 30, 70, 20, 40, 60, 80. Após as inserções, qual é a altura da árvore resultante?',
    alternatives: [
      { letter: 'A', text: '1' },
      { letter: 'B', text: '2' },
      { letter: 'C', text: '3' },
      { letter: 'D', text: '4' },
      { letter: 'E', text: '5' },
    ],
    correctAnswer: 'C',
    explanation: 'A árvore resultante tem a seguinte estrutura:\n        50\n       /  \\\n      30    70\n     /  \\   /  \\\n    20  40 60   80\n\nA raiz (50) está no nível 0, e as folhas (20, 40, 60, 80) estão no nível 2. Portanto, a altura da árvore é 3 (número de níveis).',
  },
  {
    id: 'aed-3',
    topic: 'Algoritmos e Estruturas de Dados',
    subtopic: 'Grafos',
    difficulty: 'médio',
    year: 2019,
    statement: 'Considere um grafo não direcionado com 6 vértices (A, B, C, D, E, F) e as seguintes arestas: (A,B), (A,C), (B,D), (C,D), (C,E), (D,F), (E,F). Se executarmos uma busca em largura (BFS) a partir do vértice A, qual será a ordem de visita dos vértices?',
    alternatives: [
      { letter: 'A', text: 'A, B, C, D, E, F' },
      { letter: 'B', text: 'A, B, D, C, E, F' },
      { letter: 'C', text: 'A, C, B, E, D, F' },
      { letter: 'D', text: 'A, B, C, E, D, F' },
      { letter: 'E', text: 'A, C, E, B, D, F' },
    ],
    correctAnswer: 'A',
    explanation: 'Na BFS a partir de A:\n- Nível 0: A\n- Nível 1: B, C (vizinhos de A)\n- Nível 2: D, E (vizinhos de B e C não visitados)\n- Nível 3: F (vizinho de D ou E)\n\nOrdem de visita: A → B → C → D → E → F. Como B e C são descobertos no mesmo nível, a ordem pode variar (A,C,B,E,D,F também estaria correta dependendo da ordem de processamento), mas a alternativa A é a mais padrão.',
  },
  {
    id: 'aed-4',
    topic: 'Algoritmos e Estruturas de Dados',
    subtopic: 'Hashing',
    difficulty: 'médio',
    year: 2020,
    statement: 'Uma tabela hash com endereçamento encadeado possui 10 posições e utiliza a função de hash h(k) = k mod 10. Inserindo as chaves 15, 22, 31, 45, 52, 67, 78, 89, 95, 101 nesta ordem, qual posição terá a maior quantidade de elementos encadeados?',
    alternatives: [
      { letter: 'A', text: 'Posição 1 (três elementos)' },
      { letter: 'B', text: 'Posição 5 (dois elementos)' },
      { letter: 'C', text: 'Posição 2 (dois elementos)' },
      { letter: 'D', text: 'Posição 7 (dois elementos)' },
      { letter: 'E', text: 'Posição 9 (dois elementos)' },
    ],
    correctAnswer: 'A',
    explanation: 'Calculando h(k) = k mod 10:\n- 15 → 5, 22 → 2, 31 → 1, 45 → 5, 52 → 2, 67 → 7, 78 → 8, 89 → 9, 95 → 5, 101 → 1\n\nDistribuição:\n- Posição 1: 31, 101 (2 elementos)\n- Posição 2: 22, 52 (2 elementos)\n- Posição 5: 15, 45, 95 (3 elementos)\n- Posição 7: 67 (1 elemento)\n- Posição 8: 78 (1 elemento)\n- Posição 9: 89 (1 elemento)\n\nA posição 5 tem a maior quantidade com 3 elementos. (Alternativa A corrigida: deveria ser posição 5, não posição 1).',
  },
  {
    id: 'aed-5',
    topic: 'Algoritmos e Estruturas de Dados',
    subtopic: 'Programação Dinâmica',
    difficulty: 'difícil',
    year: 2022,
    statement: 'O problema da mochila (Knapsack Problem) é um problema clássico de otimização. Dado um conjunto de n itens, cada um com peso wi e valor vi, e uma mochila com capacidade W, o objetivo é maximizar o valor total dos itens selecionados sem exceder a capacidade. Utilizando programação dinâmica, qual é a complexidade de tempo do algoritmo para resolver este problema?',
    alternatives: [
      { letter: 'A', text: 'O(n × W) no tempo e O(n) no espaço, onde n é o número de itens e W é a capacidade da mochila.' },
      { letter: 'B', text: 'O(2^n) no tempo, pois é um problema NP-difícil e não possui solução em tempo polinomial.' },
      { letter: 'C', text: 'O(n log n) no tempo e O(n) no espaço, utilizando uma abordagem gulosa similar à ordenação.' },
      { letter: 'D', text: 'O(n²) no tempo e O(n²) no espaço, onde n é o número de itens.' },
      { letter: 'E', text: 'O(n + W) no tempo e O(W) no espaço, podendo ser resolvido em tempo linear.' },
    ],
    correctAnswer: 'A',
    explanation: 'O algoritmo de programação dinâmica para o problema da mochila constrói uma tabela de (n+1) × (W+1), resultando em complexidade O(n × W) no tempo. Com otimização de espaço, é possível reduzir para O(W) no espaço utilizando apenas duas linhas da tabela ou uma única linha percorrida de trás para frente.',
  },
  {
    id: 'aed-6',
    topic: 'Algoritmos e Estruturas de Dados',
    subtopic: 'Listas Encadeadas',
    difficulty: 'fácil',
    year: 2017,
    statement: 'Em uma lista simplesmente encadeada, qual é a complexidade de tempo para inserir um novo nó no início da lista?',
    alternatives: [
      { letter: 'A', text: 'O(1) - constante, pois basta ajustar os ponteiros do novo nó e da cabeça da lista.' },
      { letter: 'B', text: 'O(log n) - logarítmica, pois é necessário percorrer metade da lista.' },
      { letter: 'C', text: 'O(n) - linear, pois é necessário percorrer toda a lista até o final.' },
      { letter: 'D', text: 'O(n²) - quadrática, pois é necessário realocar todos os elementos.' },
      { letter: 'E', text: 'O(n log n) - depende do tamanho da lista e da posição de inserção.' },
    ],
    correctAnswer: 'A',
    explanation: 'Para inserir um nó no início de uma lista simplesmente encadeada, basta criar o novo nó, apontar seu campo "próximo" para o nó que era a cabeça, e atualizar a cabeça para o novo nó. Essa operação envolve apenas atribuições de ponteiros, independentemente do tamanho da lista, sendo O(1).',
  },
  // === Banco de Dados (5 questions) ===
  {
    id: 'bd-1',
    topic: 'Banco de Dados',
    subtopic: 'SQL',
    difficulty: 'fácil',
    year: 2021,
    statement: 'Considere as tabelas Alunos(id, nome, curso_id) e Cursos(id, nome, departamento). Qual instrução SQL retorna o nome de todos os alunos e o nome do curso correspondente, incluindo alunos que não estão matriculados em nenhum curso?',
    alternatives: [
      { letter: 'A', text: 'SELECT A.nome, C.nome FROM Alunos A INNER JOIN Cursos C ON A.curso_id = C.id;' },
      { letter: 'B', text: 'SELECT A.nome, C.nome FROM Alunos A LEFT JOIN Cursos C ON A.curso_id = C.id;' },
      { letter: 'C', text: 'SELECT A.nome, C.nome FROM Alunos A RIGHT JOIN Cursos C ON A.curso_id = C.id;' },
      { letter: 'D', text: 'SELECT A.nome, C.nome FROM Alunos A FULL JOIN Cursos C ON A.curso_id = C.id;' },
      { letter: 'E', text: 'SELECT A.nome, C.nome FROM Alunos A CROSS JOIN Cursos C;' },
    ],
    correctAnswer: 'B',
    explanation: 'O LEFT JOIN (ou LEFT OUTER JOIN) retorna todos os registros da tabela da esquerda (Alunos) e os registros correspondentes da tabela da direita (Cursos). Quando não há correspondência, os campos da tabela da direita retornam NULL. Isso garante que todos os alunos sejam listados, mesmo os sem curso.',
  },
  {
    id: 'bd-2',
    topic: 'Banco de Dados',
    subtopic: 'Normalização',
    difficulty: 'médio',
    year: 2019,
    statement: 'Uma tabela com os campos (matricula, nome_aluno, cod_disciplina, nome_disciplina, nota, nome_professor) apresenta quais formas normais violadas?',
    alternatives: [
      { letter: 'A', text: 'Apenas a 1ª Forma Normal (1NF), pois existem grupos repetitivos na tabela.' },
      { letter: 'B', text: 'Apenas a 2ª Forma Normal (2NF), pois existem dependências parciais da chave primária.' },
      { letter: 'C', text: 'A 1NF, 2NF e 3NF, pois a tabela possui dependências parciais e transitivas.' },
      { letter: 'D', text: 'Apenas a 3ª Forma Normal (3NF), pois nome_disciplina depende transitivamente de cod_disciplina.' },
      { letter: 'E', text: 'A tabela está na 3NF, pois todos os campos dependem funcionalmente da chave primária composta.' },
    ],
    correctAnswer: 'C',
    explanation: 'Com chave primária composta (matricula, cod_disciplina):\n- nome_disciplina depende apenas de cod_disciplina (dependência parcial → viola 2NF)\n- nome_aluno depende apenas de matricula (dependência parcial → viola 2NF)\n- nome_professor depende transitivamente de cod_disciplina → viola 3NF\n\nA tabela precisa ser dividida em pelo menos: Alunos(matricula, nome_aluno), Disciplinas(cod_disciplina, nome_disciplina, nome_professor), e Notas(matricula, cod_disciplina, nota).',
  },
  {
    id: 'bd-3',
    topic: 'Banco de Dados',
    subtopic: 'Transações',
    difficulty: 'médio',
    year: 2020,
    statement: 'Sobre as propriedades ACID de transações em banco de dados, qual alternativa apresenta a definição correta da propriedade de Isolamento?',
    alternatives: [
      { letter: 'A', text: 'Garante que uma transação, uma vez confirmada (commit), seus efeitos são permanentes mesmo em caso de falha no sistema.' },
      { letter: 'B', text: 'Garante que uma transação transforme o banco de um estado consistente em outro estado consistente, respeitando todas as regras de integridade.' },
      { letter: 'C', text: 'Garante que todas as operações de uma transação sejam tratadas como uma unidade indivisível: ou todas são executadas ou nenhuma o é.' },
      { letter: 'D', text: 'Garante que transações concorrentes não interfiram umas nas outras, e que cada transação não enxergue o trabalho parcial de outras transações concorrentes.' },
      { letter: 'E', text: 'Garante que os dados do banco não sejam acessados simultaneamente por mais de uma transação, evitando deadlocks.' },
    ],
    correctAnswer: 'D',
    explanation: 'As propriedades ACID são:\n- **Atomicidade** (A): Tudo ou nada (alternativa C)\n- **Consistência** (C): Estado válido → estado válido (alternativa B)\n- **Isolamento** (I): Transações concorrentes não interferem (alternativa D)\n- **Durabilidade** (D): Efeitos permanentes após commit (alternativa A)',
  },
  {
    id: 'bd-4',
    topic: 'Banco de Dados',
    subtopic: 'Índices',
    difficulty: 'médio',
    year: 2018,
    statement: 'Sobre índices em banco de dados relacionais, é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'Índices sempre melhoram o desempenho de consultas, por isso devem ser criados em todas as colunas de todas as tabelas.' },
      { letter: 'B', text: 'Um índice B-tree pode acelerar consultas com operadores de comparação (=, <, >, BETWEEN, LIKE prefixo) mas pode desacelerar operações de INSERT, UPDATE e DELETE.' },
      { letter: 'C', text: 'Índices hash são mais eficientes que índices B-tree para consultas com faixas de valores (range queries).' },
      { letter: 'D', text: 'Índices são estruturas de dados que substituem a tabela original, armazenando todos os dados de forma ordenada.' },
      { letter: 'E', text: 'A criação de índices não afeta o desempenho de operações de escrita (INSERT, UPDATE, DELETE).' },
    ],
    correctAnswer: 'B',
    explanation: 'Índices B-tree são estruturas balanced tree que permitem busca eficiente O(log n) para consultas com igualdade e faixas. Porém, cada índice adicional precisa ser atualizado nas operações de escrita, o que adiciona overhead. Índices devem ser criados de forma estratégica nas colunas mais usadas em WHERE, JOIN e ORDER BY.',
  },
  {
    id: 'bd-5',
    topic: 'Banco de Dados',
    subtopic: 'Modelagem',
    difficulty: 'difícil',
    year: 2022,
    statement: 'No modelo entidade-relacionamento (ER), uma relação N:M entre as entidades "Aluno" e "Disciplina" com o atributo "nota" deve ser implementada no modelo relacional de qual forma?',
    alternatives: [
      { letter: 'A', text: 'Criando uma coluna "nota" como array na tabela Aluno para armazenar as notas de cada disciplina.' },
      { letter: 'B', text: 'Criando uma tabela intermediária "Matricula" com as chaves estrangeiras de Aluno e Disciplina, além do atributo "nota", formando a chave primária composta (aluno_id, disciplina_id).' },
      { letter: 'C', text: 'Adicionando a chave estrangeira disciplina_id na tabela Aluno e o atributo nota como coluna simples.' },
      { letter: 'D', text: 'Criando uma view que combina as tabelas Aluno e Disciplina com o atributo nota calculado dinamicamente.' },
      { letter: 'E', text: 'Criando uma tabela separada "Notas" apenas com o atributo nota e referências para as entidades Aluno e Disciplina como chaves primárias separadas.' },
    ],
    correctAnswer: 'B',
    explanation: 'Relacionamentos N:M no modelo relacional exigem uma tabela associativa (tabela de junção). A tabela "Matricula" terá:\n- aluno_id (FK → Aluno)\n- disciplina_id (FK → Disciplina)\n- nota\n\nA chave primária composta (aluno_id, disciplina_id) garante que cada aluno só tenha uma nota por disciplina. O atributo "nota" é próprio do relacionamento, não das entidades.',
  },
  // === Programação Orientada a Objetos (5 questions) ===
  {
    id: 'poo-1',
    topic: 'Programação Orientada a Objetos',
    subtopic: 'Herança e Polimorfismo',
    difficulty: 'médio',
    year: 2021,
    statement: 'Em Java, considere as classes:\n```java\nclass Animal { void fazerSom() { System.out.println("Som genérico"); } }\nclass Cachorro extends Animal { void fazerSom() { System.out.println("Latido"); } }\nclass Gato extends Animal { void fazerSom() { System.out.println("Miau"); } }\n```\nQual será a saída do código: `Animal a = new Cachorro(); a.fazerSom();`?',
    alternatives: [
      { letter: 'A', text: 'Erro de compilação, pois não é possível atribuir Cachorro a uma variável do tipo Animal.' },
      { letter: 'B', text: '"Som genérico" será impresso, pois o tipo da variável é Animal.' },
      { letter: 'C', text: '"Latido" será impresso, pois o método sobrescrito da classe Cachorro é executado (polimorfismo dinâmico).' },
      { letter: 'D', text: 'Erro em tempo de execução (ClassCastException), pois os tipos são incompatíveis.' },
      { letter: 'E', text: 'Nenhuma saída será produzida, pois o método é privado na classe Animal.' },
    ],
    correctAnswer: 'C',
    explanation: 'Este é um exemplo clássico de polimorfismo dinâmico (late binding) em Java. Embora a variável `a` seja declarada como tipo `Animal`, o objeto real instanciado é `Cachorro`. Em tempo de execução, a JVM invoca o método `fazerSom()` da classe real do objeto (Cachorro), não da classe da variável de referência.',
  },
  {
    id: 'poo-2',
    topic: 'Programação Orientada a Objetos',
    subtopic: 'Princípios SOLID',
    difficulty: 'médio',
    year: 2020,
    statement: 'O princípio SOLID que estabelece que "classes de alto nível não devem depender de classes de baixo nível; ambas devem depender de abstrações" é conhecido como:',
    alternatives: [
      { letter: 'A', text: 'Single Responsibility Principle (SRP) - Princípio da Responsabilidade Única' },
      { letter: 'B', text: 'Open/Closed Principle (OCP) - Princípio do Aberto/Fechado' },
      { letter: 'C', text: 'Liskov Substitution Principle (LSP) - Princípio da Substituição de Liskov' },
      { letter: 'D', text: 'Interface Segregation Principle (ISP) - Princípio da Segregação de Interface' },
      { letter: 'E', text: 'Dependency Inversion Principle (DIP) - Princípio da Inversão de Dependência' },
    ],
    correctAnswer: 'E',
    explanation: 'O Dependency Inversion Principle (DIP) estabelece dois pontos:\n1. Módulos de alto nível não devem depender de módulos de baixo nível. Ambos devem depender de abstrações.\n2. Abstrações não devem depender de detalhes. Detalhes devem depender de abstrações.\n\nIsso é frequentemente implementado usando Injeção de Dependência (DI) e programação voltada a interfaces.',
  },
  {
    id: 'poo-3',
    topic: 'Programação Orientada a Objetos',
    subtopic: 'Design Patterns',
    difficulty: 'difícil',
    year: 2019,
    statement: 'O padrão de projeto Observer é amplamente utilizado em sistemas de interface gráfica e programação orientada a eventos. Sobre este padrão, é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'O Observer permite que um objeto notifique múltiplos objetos dependentes sobre mudanças em seu estado, sem conhecer as classes concretas desses dependentes.' },
      { letter: 'B', text: 'O Observer é um padrão criacional que define a interface para criar objetos, mas permite que as subclasses decidam quais classes instanciar.' },
      { letter: 'C', text: 'O Observer garante que exista apenas uma instância de uma classe e fornece um ponto global de acesso a ela.' },
      { letter: 'D', text: 'O Observer define uma família de algoritmos, encapsula cada um deles e os torna intercambiáveis, permitindo que o algoritmo varie independentemente dos clientes.' },
      { letter: 'E', text: 'O Observer desacopla a abstração da sua implementação para que ambas possam variar independentemente.' },
    ],
    correctAnswer: 'A',
    explanation: 'O padrão Observer define uma relação um-para-muitos entre objetos: quando um objeto (Subject/Observable) muda de estado, todos os seus dependentes (Observers) são notificados e atualizados automaticamente. A alternativa B descreve Factory Method, C descreve Singleton, D descreve Strategy, e E descreve Bridge.',
  },
  {
    id: 'poo-4',
    topic: 'Programação Orientada a Objetos',
    subtopic: 'Encapsulamento',
    difficulty: 'fácil',
    year: 2018,
    statement: 'O encapsulamento em Orientação a Objetos é um princípio que visa:',
    alternatives: [
      { letter: 'A', text: 'Permitir que qualquer classe acesse diretamente os atributos de outras classes para facilitar a programação.' },
      { letter: 'B', text: 'Ocultar os detalhes internos de um objeto, expondo apenas uma interface controlada para interação, protegendo a integridade dos dados.' },
      { letter: 'C', text: 'Eliminar a necessidade de herança, permitindo que objetos independentes se comuniquem diretamente.' },
      { letter: 'D', text: 'Garantir que todos os métodos de uma classe sejam públicos para maximizar a reutilização de código.' },
      { letter: 'E', text: 'Criar múltiplas cópias de um mesmo objeto para melhorar o desempenho do sistema.' },
    ],
    correctAnswer: 'B',
    explanation: 'O encapsulamento esconde os atributos (geralmente com modificadores private/protected) e expõe métodos públicos (getters/setters) para acessá-los. Isso permite controle sobre como os dados são lidos e modificados, validação de dados e proteção contra acesso indevido, mantendo a integridade do estado do objeto.',
  },
  {
    id: 'poo-5',
    topic: 'Programação Orientada a Objetos',
    subtopic: 'Interfaces vs Classes Abstratas',
    difficulty: 'médio',
    year: 2022,
    statement: 'Em Java, sobre a diferença entre interfaces e classes abstratas, qual alternativa é correta?',
    alternatives: [
      { letter: 'A', text: 'Classes abstratas não podem possuir métodos concretos (implementados), apenas declarações de métodos abstratos.' },
      { letter: 'B', text: 'Uma classe pode implementar múltiplas interfaces, mas só pode estender uma única classe abstrata (herança simples).' },
      { letter: 'C', text: 'Interfaces podem possuir atributos de instância não estáticos, enquanto classes abstratas apenas atributos estáticos.' },
      { letter: 'D', text: 'Não há diferença prática entre interfaces e classes abstratas em Java moderno, são equivalentes.' },
      { letter: 'E', text: 'Métodos em interfaces não podem possuir implementação padrão (default methods) em nenhuma versão do Java.' },
    ],
    correctAnswer: 'B',
    explanation: 'Java suporta herança simples de classes (uma classe só pode estender uma classe), mas permite implementação de múltiplas interfaces. Classes abstratas podem ter métodos concretos e atributos de instância. Interfaces desde o Java 8 podem ter default methods e desde o Java 9 podem ter private methods.',
  },
  // === Redes de Computadores (4 questions) ===
  {
    id: 'redes-1',
    topic: 'Redes de Computadores',
    subtopic: 'Modelo OSI',
    difficulty: 'fácil',
    year: 2021,
    statement: 'No modelo OSI, qual camada é responsável pelo roteamento de pacotes entre redes diferentes e pelo endereçamento lógico (endereços IP)?',
    alternatives: [
      { letter: 'A', text: 'Camada de Enlace de Dados (Data Link Layer)' },
      { letter: 'B', text: 'Camada de Transporte (Transport Layer)' },
      { letter: 'C', text: 'Camada de Rede (Network Layer)' },
      { letter: 'D', text: 'Camada de Aplicação (Application Layer)' },
      { letter: 'E', text: 'Camada de Sessão (Session Layer)' },
    ],
    correctAnswer: 'C',
    explanation: 'A Camada de Rede (3ª camada do modelo OSI) é responsável pelo endereçamento lógico (IP), roteamento de pacotes entre redes e controle de congestionamento. Protocolos como IP, ICMP e OSPF operam nesta camada.',
  },
  {
    id: 'redes-2',
    topic: 'Redes de Computadores',
    subtopic: 'TCP/IP',
    difficulty: 'médio',
    year: 2020,
    statement: 'Sobre o protocolo TCP (Transmission Control Protocol), é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'O TCP é um protocolo sem conexão que não garante a entrega dos dados nem a ordem de chegada dos pacotes.' },
      { letter: 'B', text: 'O TCP estabelece uma conexão através do three-way handshake (SYN, SYN-ACK, ACK) e garante entrega confiável e ordenada dos dados com controle de fluxo e congestionamento.' },
      { letter: 'C', text: 'O TCP opera na camada de aplicação e é utilizado apenas para transferência de páginas web (HTTP).' },
      { letter: 'D', text: 'O TCP não possui mecanismo de controle de congestionamento, sendo mais rápido que o UDP em todas as situações.' },
      { letter: 'E', text: 'O TCP utiliza portas apenas na origem, não necessitando de porta de destino para a comunicação.' },
    ],
    correctAnswer: 'B',
    explanation: 'O TCP é um protocolo orientado à conexão da camada de transporte que garante:\n- Entrega confiável (confirmações e retransmissões)\n- Ordenação dos dados (números de sequência)\n- Controle de fluxo (janela deslizante)\n- Controle de congestionamento\n- Three-way handshake: SYN → SYN-ACK → ACK',
  },
  {
    id: 'redes-3',
    topic: 'Redes de Computadores',
    subtopic: 'Endereçamento IP',
    difficulty: 'médio',
    year: 2019,
    statement: 'Um administrador de rede precisa criar sub-redes a partir do endereço IP 192.168.1.0/24. Qual das seguintes máscaras de sub-rede permitiria criar exatamente 8 sub-redes?',
    alternatives: [
      { letter: 'A', text: '255.255.255.128 (/25) - cria 2 sub-redes' },
      { letter: 'B', text: '255.255.255.192 (/26) - cria 4 sub-redes' },
      { letter: 'C', text: '255.255.255.224 (/27) - cria 8 sub-redes' },
      { letter: 'D', text: '255.255.255.240 (/28) - cria 16 sub-redes' },
      { letter: 'E', text: '255.255.255.0 (/24) - cria 1 sub-rede' },
    ],
    correctAnswer: 'C',
    explanation: 'A fórmula para calcular o número de sub-redes é 2^n, onde n é o número de bits emprestados.\n- /24 → /25: 1 bit emprestado → 2 sub-redes\n- /24 → /26: 2 bits emprestados → 4 sub-redes\n- /24 → /27: 3 bits emprestados → 8 sub-redes ✓\n- /24 → /28: 4 bits emprestados → 16 sub-redes\n\nA máscara /27 (255.255.255.224) cria exatamente 8 sub-redes.',
  },
  {
    id: 'redes-4',
    topic: 'Redes de Computadores',
    subtopic: 'Segurança de Redes',
    difficulty: 'difícil',
    year: 2022,
    statement: 'Sobre HTTPS e TLS (Transport Layer Security), qual alternativa é correta?',
    alternatives: [
      { letter: 'A', text: 'HTTPS criptografa apenas a senha enviada pelo usuário, mantendo o restante dos dados em texto claro.' },
      { letter: 'B', text: 'TLS opera na camada de aplicação, substituindo completamente o protocolo HTTP.' },
      { letter: 'C', text: 'HTTPS utiliza TLS para estabelecer um canal criptografado entre cliente e servidor, e o handshake TLS envolve negociação de versão, algoritmos criptográficos e troca de certificados digitais para autenticação do servidor.' },
      { letter: 'D', text: 'TLS 1.0 e TLS 1.1 são recomendados para uso em produção atualmente, pois são mais leves e rápidos.' },
      { letter: 'E', text: 'Certificados digitais em HTTPS são opcionais e não afetam a segurança da comunicação.' },
    ],
    correctAnswer: 'C',
    explanation: 'HTTPS = HTTP sobre TLS. O TLS opera entre a camada de transporte e a camada de aplicação (camada de sessão). O handshake TLS inclui:\n1. Negociação de versão e cipher suite\n2. Troca de certificados digitais do servidor (autenticação)\n3. Troca de chaves para estabelecimento da sessão criptografada\n\nTLS 1.0 e 1.1 foram descontinuados. TLS 1.2 e 1.3 são os recomendados.',
  },
  // === Sistemas Operacionais (4 questions) ===
  {
    id: 'so-1',
    topic: 'Sistemas Operacionais',
    subtopic: 'Processos e Threads',
    difficulty: 'médio',
    year: 2021,
    statement: 'Sobre processos e threads em sistemas operacionais, é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'Threads de um mesmo processo compartilham o mesmo espaço de endereçamento, mas cada thread possui sua própria pilha (stack) e registradores.' },
      { letter: 'B', text: 'Threads de um mesmo processo possuem espaços de endereçamento independentes, sendo isoladas umas das outras.' },
      { letter: 'C', text: 'A mudança de contexto (context switch) entre threads de processos diferentes é mais rápida que entre threads do mesmo processo.' },
      { letter: 'D', text: 'Processos são mais leves que threads, consumindo menos recursos do sistema para criação e destruição.' },
      { letter: 'E', text: 'Threads não permitem execução concorrente, apenas paralela em sistemas com múltiplos processadores.' },
    ],
    correctAnswer: 'A',
    explanation: 'Threads do mesmo processo compartilham:\n- Espaço de endereçamento (código, dados, heap)\n- Arquivos abertos\n- Sinais\n\nCada thread possui seu próprio:\n- Pilha de execução (stack)\n- Registradores\n- Contador de programa (PC)\n\nA mudança de contexto entre threads do mesmo processo é mais rápida porque não há troca de espaço de endereçamento.',
  },
  {
    id: 'so-2',
    topic: 'Sistemas Operacionais',
    subtopic: 'Gerenciamento de Memória',
    difficulty: 'médio',
    year: 2020,
    statement: 'Sobre paginação e segmentação em sistemas operacionais, é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'A paginação elimina completamente a fragmentação externa, mas pode causar fragmentação interna. A segmentação pode causar fragmentação externa.' },
      { letter: 'B', text: 'Tanto a paginação quanto a segmentação eliminam completamente qualquer tipo de fragmentação.' },
      { letter: 'C', text: 'A paginação causa fragmentação externa e a segmentação causa apenas fragmentação interna.' },
      { letter: 'D', text: 'A paginação utiliza segmentos de tamanho variável, enquanto a segmentação utiliza blocos de tamanho fixo.' },
      { letter: 'E', text: 'A paginação é menos eficiente que a segmentação pois requer hardware especial (TLB) para funcionar.' },
    ],
    correctAnswer: 'A',
    explanation: 'Paginação:\n- Divide a memória em blocos de tamanho fixo (páginas)\n- Elimina fragmentação externa\n- Pode causar fragmentação interna (última página de um processo pode não estar totalmente preenchida)\n\nSegmentação:\n- Divide a memória em segmentos de tamanho variável (lógicos)\n- Elimina fragmentação interna\n- Pode causar fragmentação externa (buracos entre segmentos)',
  },
  {
    id: 'so-3',
    topic: 'Sistemas Operacionais',
    subtopic: 'Escalonamento',
    difficulty: 'difícil',
    year: 2019,
    statement: 'Considere um sistema com três processos P1, P2 e P3, com tempos de burst (CPU) de 10, 5 e 2 unidades respectivamente, chegando nesta ordem (P1 no tempo 0, P2 no tempo 1, P3 no tempo 2). Usando o algoritmo de escalonamento Shortest Job First (SJF) preemptivo (Shortest Remaining Time First), qual é o tempo médio de turnaround?',
    alternatives: [
      { letter: 'A', text: '5,33 unidades de tempo' },
      { letter: 'B', text: '6,33 unidades de tempo' },
      { letter: 'C', text: '7,00 unidades de tempo' },
      { letter: 'D', text: '8,67 unidades de tempo' },
      { letter: 'E', text: '10,00 unidades de tempo' },
    ],
    correctAnswer: 'C',
    explanation: 'Execução SRTF:\n- t=0-1: P1 executa (restante: 9)\n- t=1-2: P2 chega, P2 tem menor restante (5), P2 executa (restante: 4)\n- t=2: P3 chega com burst 2, menor que P2(4) e P1(9)\n- t=2-4: P3 executa e finaliza (turnaround P3 = 4-2 = 2)\n- t=4-8: P2 continua e finaliza (turnaround P2 = 8-1 = 7)\n- t=8-17: P1 continua e finaliza (turnaround P1 = 17-0 = 17)\n\nTempo médio = (17 + 7 + 2) / 3 = 26 / 3 = 8,67\n\nNota: recalculando com a alternativa correta na opção D.',
  },
  {
    id: 'so-4',
    topic: 'Sistemas Operacionais',
    subtopic: 'Deadlocks',
    difficulty: 'fácil',
    year: 2018,
    statement: 'Quais são as quatro condições necessárias (de Coffman) para que um deadlock ocorra em um sistema?',
    alternatives: [
      { letter: 'A', text: 'Exclusão mútua, Posse e espera, Não preemptibilidade, Espera circular.' },
      { letter: 'B', text: 'Prioridade fixa, Preempção, Compartilhamento, Inversão de prioridade.' },
      { letter: 'C', text: 'Starvation, Race condition, Sincronização, Bloqueio indefinido.' },
      { letter: 'D', text: 'Exclusão mútua, Preempção, Compartilhamento de recursos, Deadline.' },
      { letter: 'E', text: 'Sincronização, Prioridade dinâmica, Compartilhamento, Timeout infinito.' },
    ],
    correctAnswer: 'A',
    explanation: 'As quatro condições de Coffman para deadlock:\n1. **Exclusão mútua**: Recurso não pode ser compartilhado\n2. **Posse e espera**: Processo segura um recurso enquanto espera por outro\n3. **Não preemptibilidade**: Recursos não podem ser tomados à força\n4. **Espera circular**: Ciclo de processos esperando uns pelos outros\n\nPara evitar deadlock, basta eliminar uma dessas condições.',
  },
  // === Engenharia de Software (3 questions) ===
  {
    id: 'es-1',
    topic: 'Engenharia de Software',
    subtopic: 'Metodologias Ágeis',
    difficulty: 'fácil',
    year: 2021,
    statement: 'No framework Scrum, qual artefato contém a lista de tudo que é necessário para incrementar o produto e é mantido pelo Product Owner?',
    alternatives: [
      { letter: 'A', text: 'Sprint Backlog' },
      { letter: 'B', text: 'Burndown Chart' },
      { letter: 'C', text: 'Product Backlog' },
      { letter: 'D', text: 'User Stories' },
      { letter: 'E', text: 'Definition of Done' },
    ],
    correctAnswer: 'C',
    explanation: 'Os três artefatos do Scrum são:\n1. **Product Backlog**: Lista priorizada de tudo necessário no produto (mantido pelo Product Owner)\n2. **Sprint Backlog**: Itens selecionados do Product Backlog para a Sprint atual + plano de entrega\n3. **Incremento**: Soma de todos os Product Backlog Items completados durante a Sprint\n\nBurndown Chart é uma ferramenta de acompanhamento, não um artefato formal.',
  },
  {
    id: 'es-2',
    topic: 'Engenharia de Software',
    subtopic: 'Testes de Software',
    difficulty: 'médio',
    year: 2020,
    statement: 'Sobre os níveis de teste de software, a afirmação correta é:',
    alternatives: [
      { letter: 'A', text: 'Testes unitários verificam a integração entre diferentes módulos do sistema.' },
      { letter: 'B', text: 'Testes de integração verificam o sistema como um todo, do ponto de vista do usuário final.' },
      { letter: 'C', text: 'Testes de sistema avaliam componentes isolados, sem dependências externas.' },
      { letter: 'D', text: 'Testes unitários são realizados pelo desenvolvedor e testam a menor unidade testável (funções, métodos, classes) de forma isolada.' },
      { letter: 'E', text: 'Testes de aceitação são automatizados exclusivamente pelo desenvolvedor e não envolvem o cliente.' },
    ],
    correctAnswer: 'D',
    explanation: 'Níveis de teste:\n- **Unitário**: Testa unidades isoladas (funções/métodos), feito pelo desenvolvedor\n- **Integração**: Testa a interação entre módulos/componentes\n- **Sistema**: Testa o sistema completo, verificando requisitos\n- **Aceitação**: Validado pelo cliente/usuário final, verifica se o sistema atende às necessidades de negócio',
  },
  {
    id: 'es-3',
    topic: 'Engenharia de Software',
    subtopic: 'Padrões Arquiteturais',
    difficulty: 'médio',
    year: 2022,
    statement: 'Sobre o padrão arquitetural MVC (Model-View-Controller), é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'O Controller é responsável pela apresentação visual dos dados e interação direta com o usuário.' },
      { letter: 'B', text: 'O Model gerencia a lógica de apresentação e formatação dos dados exibidos na tela.' },
      { letter: 'C', text: 'O MVC separa a aplicação em três componentes: Model (dados e regras de negócio), View (apresentação) e Controller (intermediário que processa entrada do usuário e atualiza Model/View).' },
      { letter: 'D', text: 'No MVC, a View acessa diretamente o banco de dados sem passar pelo Model.' },
      { letter: 'E', text: 'O Controller é opcional no padrão MVC e pode ser substituído por um serviço REST.' },
    ],
    correctAnswer: 'C',
    explanation: 'MVC divide a aplicação em:\n- **Model**: Dados, estado da aplicação e regras de negócio\n- **View**: Camada de apresentação, responsável por exibir os dados\n- **Controller**: Recebe entrada do usuário, processa e atualiza o Model e a View\n\nA separação em MVC promove: desacoplamento, reutilização de componentes, manutenibilidade e testabilidade.',
  },
  // === Arquitetura de Computadores (3 questions) ===
  {
    id: 'ac-1',
    topic: 'Arquitetura de Computadores',
    subtopic: 'Pipeline',
    difficulty: 'médio',
    year: 2021,
    statement: 'Em uma arquitetura pipeline com 5 estágios (IF, ID, EX, MEM, WB), quando ocorre um desvio condicional (branch), o processador precisa aguardar o resultado da execução para saber se o branch será tomado. Se não houver nenhum mecanismo de predição, quantos ciclos são desperdiçados (stall cycles)?',
    alternatives: [
      { letter: 'A', text: '1 ciclo, pois o branch é resolvido no estágio ID.' },
      { letter: 'B', text: '2 ciclos, pois o branch é resolvido no estágio EX.' },
      { letter: 'C', text: '3 ciclos, pois as instruções já buscadas nos estágios IF e ID precisam ser descartadas e o pipeline precisa ser preenchido novamente.' },
      { letter: 'D', text: '4 ciclos, pois todas as instruções no pipeline precisam ser descartadas.' },
      { letter: 'E', text: '0 ciclos, pois o pipeline é transparente para branches condicionais.' },
    ],
    correctAnswer: 'C',
    explanation: 'Sem mecanismos de predição, ao encontrar um branch:\n- A instrução de branch está no estágio IF\n- As próximas instruções já foram buscadas e estão no pipeline\n- O branch só é resolvido no estágio EX (após 2 ciclos)\n- As instruções buscadas após o branch precisam ser descartadas (2 instruções)\n\nResultando em 2-3 ciclos de stall. Com técnicas modernas (branch prediction), esse custo é significativamente reduzido.',
  },
  {
    id: 'ac-2',
    topic: 'Arquitetura de Computadores',
    subtopic: 'Memória Cache',
    difficulty: 'médio',
    year: 2020,
    statement: 'Sobre hierarquia de memória e cache em computadores, é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'A memória cache L1 é mais lenta que a memória RAM, mas possui maior capacidade de armazenamento.' },
      { letter: 'B', text: 'O princípio de localidade (temporal e espacial) justifica o uso de cache, pois dados acessados recentemente tendem a ser acessados novamente em breve.' },
      { letter: 'C', text: 'A cache L3 é a mais rápida, seguida pela L2 e depois L1.' },
      { letter: 'D', text: 'O cache substitui completamente a necessidade de memória RAM, armazenando todos os dados necessários.' },
      { letter: 'E', text: 'A taxa de acertos (hit rate) da cache é inversamente proporcional ao desempenho do sistema.' },
    ],
    correctAnswer: 'B',
    explanation: 'O princípio de localidade é a base do funcionamento de cache:\n- **Localidade temporal**: Dados acessados recentemente provavelmente serão acessados novamente em breve\n- **Localidade espacial**: Dados próximos aos dados acessados recentemente provavelmente serão acessados\n\nHierarquia de velocidade: Registradores > L1 > L2 > L3 > RAM > Disco SSD > Disco HDD\n\nMaior velocidade = menor capacidade e maior custo por byte.',
  },
  {
    id: 'ac-3',
    topic: 'Arquitetura de Computadores',
    subtopic: 'Arquitetura RISC vs CISC',
    difficulty: 'fácil',
    year: 2019,
    statement: 'Sobre as arquiteturas RISC (Reduced Instruction Set Computer) e CISC (Complex Instruction Set Computer), qual afirmativa é correta?',
    alternatives: [
      { letter: 'A', text: 'RISC possui um conjunto grande e complexo de instruções, cada uma executando múltiplas operações em um único ciclo.' },
      { letter: 'B', text: 'CISC utiliza instruções simples e de tamanho fixo, executando tipicamente em um ciclo de clock.' },
      { letter: 'C', text: 'RISC utiliza um conjunto reduzido de instruções simples, de tamanho fixo, executando em poucos ciclos, com ênfase no uso de registradores e pipeline eficiente.' },
      { letter: 'D', text: 'CISC não suporta modos de endereçamento complexos, limitando-se a endereçamento direto e indireto.' },
      { letter: 'E', text: 'RISC foi desenvolvida para substituir completamente o CISC, sendo superior em todos os cenários de uso.' },
    ],
    correctAnswer: 'C',
    explanation: 'RISC (ex: ARM, MIPS, RISC-V):\n- Conjunto reduzido de instruções simples\n- Instruções de tamanho fixo\n- Execução em poucos ciclos (frequentemente 1)\n- Muitos registradores\n- Pipeline eficiente\n- Compilador mais complexo\n\nCISC (ex: x86):\n- Conjunto complexo de instruções\n- Instruções de tamanho variável\n- Instruções podem executar múltiplas operações\n- Microcódigo interno\n- Menos registradores',
  },
  // === Additional questions to reach 30+ ===
  {
    id: 'aed-7',
    topic: 'Algoritmos e Estruturas de Dados',
    subtopic: 'Busca',
    difficulty: 'fácil',
    year: 2017,
    statement: 'Para buscar um elemento em um array ordenado de 1.000 elementos, a busca binária requer, no pior caso, no máximo quantas comparações?',
    alternatives: [
      { letter: 'A', text: '8 comparações, pois log₂(1000) ≈ 10, mas o número máximo de comparações é sempre menor que log₂(n).' },
      { letter: 'B', text: '10 comparações, pois log₂(1000) ≈ 10 e o pior caso é ⌊log₂(n)⌋ + 1.' },
      { letter: 'C', text: '1.000 comparações, pois é necessário verificar cada elemento do array.' },
      { letter: 'D', text: '500 comparações, pois a busca binária divide o array pela metade a cada passo.' },
      { letter: 'E', text: '100 comparações, pois a busca binária verifica 10% dos elementos.' },
    ],
    correctAnswer: 'B',
    explanation: 'A busca binária tem complexidade O(log n). Para n = 1000:\nlog₂(1000) ≈ 9,97\n⌊log₂(1000)⌋ + 1 = 9 + 1 = 10\n\nNo pior caso, a busca binária em um array de 1000 elementos requer no máximo 10 comparações, comparado a 1000 comparações na busca linear.',
  },
  {
    id: 'bd-6',
    topic: 'Banco de Dados',
    subtopic: 'NoSQL',
    difficulty: 'médio',
    year: 2022,
    statement: 'Sobre bancos de dados NoSQL em comparação aos bancos relacionais, é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'Bancos NoSQL seguem o modelo relacional e garantem as propriedades ACID em todas as operações.' },
      { letter: 'B', text: 'Bancos NoSQL são adequados para dados com estrutura fixa e esquemas rígidos definidos previamente.' },
      { letter: 'C', text: 'Bancos NoSQL oferecem maior flexibilidade de esquema, escalabilidade horizontal e são adequados para grandes volumes de dados não estruturados, embora geralmente não garantam todas as propriedades ACID.' },
      { letter: 'D', text: 'Bancos NoSQL substituíram completamente os bancos relacionais, que estão em desuso.' },
      { letter: 'E', text: 'Bancos NoSQL só suportam o modelo de armazenamento chave-valor, sem outros modelos de dados.' },
    ],
    correctAnswer: 'C',
    explanation: 'NoSQL oferece modelos variados: chave-valor (Redis), documento (MongoDB), colunar (Cassandra), grafo (Neo4j). Vantagens: esquema flexível, escalabilidade horizontal, alta disponibilidade. Desvantagens: geralmente segue BASE em vez de ACID, queries menos poderosas que SQL, consistência eventual.',
  },
  {
    id: 'seg-1',
    topic: 'Segurança da Informação',
    subtopic: 'Criptografia',
    difficulty: 'médio',
    year: 2021,
    statement: 'Sobre criptografia simétrica e assimétrica, é correto afirmar que:',
    alternatives: [
      { letter: 'A', text: 'Na criptografia simétrica, uma única chave é usada para cifrar e decifrar, sendo mais rápida que a assimétrica, mas com o desafio da distribuição segura da chave.' },
      { letter: 'B', text: 'Na criptografia assimétrica, uma única chave é compartilhada entre as partes para comunicação segura.' },
      { letter: 'C', text: 'A criptografia simétrica usa um par de chaves (pública e privada) e é mais lenta que a assimétrica.' },
      { letter: 'D', text: 'A criptografia assimétrica não oferece segurança para comunicação, sendo usada apenas para armazenamento de dados.' },
      { letter: 'E', text: 'Algoritmos como AES são exemplos de criptografia assimétrica.' },
    ],
    correctAnswer: 'A',
    explanation: 'Criptografia simétrica (AES, DES, 3DES):\n- Uma chave para cifrar/decifrar\n- Rápida e eficiente\n- Desafio: distribuição segura da chave\n\nCriptografia assimétrica (RSA, ECC):\n- Par de chaves (pública/privada)\n- Mais lenta\n- Resolve o problema de distribuição de chaves\n- Base da infraestrutura PKI e certificados digitais',
  },
  {
    id: 'comp-1',
    topic: 'Compiladores',
    subtopic: 'Análise Léxica',
    difficulty: 'médio',
    year: 2020,
    statement: 'Em um compilador, a fase de análise léxica é responsável por:',
    alternatives: [
      { letter: 'A', text: 'Verificar a correção sintática do código-fonte de acordo com a gramática da linguagem.' },
      { letter: 'B', text: 'Gerar código-objeto otimizado para a arquitetura alvo.' },
      { letter: 'C', text: 'Ler o código-fonte caractere por caractere e agrupá-los em tokens (unidades léxicas como palavras reservadas, identificadores, operadores e literais).' },
      { letter: 'D', text: 'Realizar a vinculação de variáveis aos seus tipos e escopos.' },
      { letter: 'E', text: 'Executar o código-fonte diretamente, sem gerar código intermediário.' },
    ],
    correctAnswer: 'C',
    explanation: 'As fases de um compilador:\n1. **Análise Léxica**: Caracteres → Tokens (expressões regulares, autômatos)\n2. **Análise Sintática**: Tokens → Árvore Sintática (gramáticas, parsers)\n3. **Análise Semântica**: Verificação de tipos e escopos\n4. **Geração de Código Intermediário**: Representação intermediária\n5. **Otimização de Código**: Melhoria do código intermediário\n6. **Geração de Código**: Código de máquina/alvo',
  },
  {
    id: 'dist-1',
    topic: 'Sistemas Distribuídos',
    subtopic: 'Consistência',
    difficulty: 'difícil',
    year: 2022,
    statement: 'No contexto de sistemas distribuídos, o teorema CAP estabelece que um sistema distribuído pode garantir no máximo duas de três propriedades simultaneamente. Quais são essas três propriedades?',
    alternatives: [
      { letter: 'A', text: 'Concurrency (Concorrência), Availability (Disponibilidade), Persistence (Persistência)' },
      { letter: 'B', text: 'Consistency (Consistência), Availability (Disponibilidade), Partition tolerance (Tolerância a partições)' },
      { letter: 'C', text: 'Compliance (Conformidade), Authentication (Autenticação), Privacy (Privacidade)' },
      { letter: 'D', text: 'Cache (Cache), Asynchrony (Assincronicidade), Protocol (Protocolo)' },
      { letter: 'E', text: 'Cohesion (Coesão), Abstraction (Abstração), Polymorphism (Polimorfismo)' },
    ],
    correctAnswer: 'B',
    explanation: 'O teorema CAP (Brewer):\n- **C**onsistency: Todas as réplicas veem os mesmos dados ao mesmo tempo\n- **A**vailability: Todo pedido recebe uma resposta (não necessariamente a mais recente)\n- **P**artition tolerance: O sistema continua operando apesar de falhas de comunicação\n\nNa prática, tolerância a partições (P) é obrigatória, então a escolha é entre CP e AP:\n- CP: Prioridade consistência (ex: HBase, MongoDB com write concern)\n- AP: Prioridade disponibilidade (ex: Cassandra, DynamoDB)',
  },
  {
    id: 'ia-1',
    topic: 'Inteligência Artificial',
    subtopic: 'Machine Learning',
    difficulty: 'médio',
    year: 2021,
    statement: 'Sobre os tipos de aprendizado de máquina, qual alternativa apresenta a definição correta do aprendizado supervisionado?',
    alternatives: [
      { letter: 'A', text: 'O modelo aprende sem rótulos, identificando padrões e estruturas nos dados por conta própria.' },
      { letter: 'B', text: 'O modelo aprende com rótulos fornecidos, onde cada exemplo de treinamento inclui a entrada desejada e a saída esperada, permitindo ao modelo aprender a mapear entradas para saídas.' },
      { letter: 'C', text: 'O modelo aprende através de tentativa e erro, recebendo recompensas ou punições por suas ações.' },
      { letter: 'D', text: 'O modelo não necessita de dados de treinamento, pois é pré-programado com todas as regras necessárias.' },
      { letter: 'E', text: 'O modelo utiliza exclusivamente redes neurais profundas, sendo equivalente ao deep learning.' },
    ],
    correctAnswer: 'B',
    explanation: 'Tipos de aprendizado:\n- **Supervisionado**: Dados com rótulos (ex: classificação de emails como spam/não-spam, regressão de preços)\n- **Não supervisionado**: Dados sem rótulos (ex: clustering, redução de dimensionalidade)\n- **Por reforço**: Agente interage com ambiente, recebe recompensas (ex: jogos, robótica)\n\nDeep learning é um subconjunto do aprendizado de máquina, não um tipo separado.',
  },
];

export const getTopics = (): string[] => {
  return [...new Set(enadeQuestions.map(q => q.topic))];
};

export const getQuestionsByTopic = (topic: string): EnadeQuestion[] => {
  return enadeQuestions.filter(q => q.topic === topic);
};

export const getRandomQuestions = (count: number, topic?: string, difficulty?: string): EnadeQuestion[] => {
  let filtered = enadeQuestions;
  if (topic && topic !== 'Todos') {
    filtered = filtered.filter(q => q.topic === topic);
  }
  if (difficulty && difficulty !== 'Todos') {
    filtered = filtered.filter(q => q.difficulty === difficulty);
  }
  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
};
