/*
=============================================================================
EnadIA TECH — Supabase PostgreSQL Migration
=============================================================================

MULTI-TENANCY ARCHITECTURE
==========================
This schema supports a multi-tenancy model via an `instance` column on key
tables (users, student_responses, local_question_responses, essay_answers).

  • Each row belongs to exactly one "instance" (tenant), identified by a TEXT
    value such as 'ENADIA', 'UNIP', 'ESTACIO', etc.
  • The default instance is 'ENADIA', representing the original EnadIA platform.
  • Business logic in the application layer is responsible for filtering queries
    by the current user's instance — no Row Level Security (RLS) is used because
    the app implements its own custom JWT authentication (not Supabase Auth).
  • Composite unique constraints on (email, instance) and (ra, instance) allow
    the same email or RA to exist in different tenants without conflict.
  • Indexes on `instance` are added to all tenant-scoped tables for efficient
    filtering.

ID CONVENTION
==============
  • All primary keys use TEXT to store CUID strings generated by the
    application layer (e.g. `cuid()` from the `@paralleldrive/cuid2` library).
  • UUIDs are NOT used anywhere in this schema.

ENUM POLICY
============
  • PostgreSQL ENUM types are NOT used. All constrained string columns use
    TEXT with CHECK constraints for maximum flexibility and easier migrations.

AUTHENTICATION
==============
  • The application uses custom JWT-based authentication (bcrypt passwords,
    signed JWTs issued by the Next.js API). Supabase Auth is NOT used.
  • Consequently, no RLS policies, no auth.uid() references, and no
    anon/auth role grants are present in this schema.

=============================================================================
*/


-- ============================================================================
-- SECTION 1: HELPER FUNCTIONS
-- ============================================================================

-- Auto-update `updated_at` timestamp on every row modification.
-- Attach this trigger to any table that has an `updated_at` column.
CREATE OR REPLACE FUNCTION public.trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- SECTION 2: TABLES
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 2.1  users
-- ---------------------------------------------------------------------------
-- Central identity table. The `instance` column enables the same email / RA
-- to exist in different tenants. Role is constrained via CHECK.

CREATE TABLE public.users (
  id            TEXT    PRIMARY KEY,                          -- CUID generated by app
  instance      TEXT    NOT NULL DEFAULT 'ENADIA',
  email         TEXT    NOT NULL,
  name          TEXT    NOT NULL,
  password      TEXT    NOT NULL,                             -- bcrypt hash
  role          TEXT    NOT NULL DEFAULT 'ALUNO'
                CHECK (role IN ('MASTER', 'PROFESSOR', 'ALUNO')),
  ra            TEXT,                                          -- academic registration
  avatar        TEXT,
  active        BOOLEAN NOT NULL DEFAULT true,
  last_login    TIMESTAMPTZ,

  -- Student-specific fields
  curso         TEXT,                                          -- course name
  periodo       INTEGER,                                       -- semester / period
  modalidade    TEXT    DEFAULT 'PRESENCIAL'
                CHECK (modalidade IN ('EAD', 'PRESENCIAL', 'SEMIPRESENCIAL')),

  -- Professor-specific fields
  disciplina    TEXT,                                          -- professor's subject

  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Constraints
  CONSTRAINT uq_users_email_instance  UNIQUE (email, instance),
  CONSTRAINT uq_users_ra_instance    UNIQUE (ra, instance)
);

-- ---------------------------------------------------------------------------
-- 2.2  microareas
-- ---------------------------------------------------------------------------
-- Content categories / knowledge areas for the ENADE exam.

CREATE TABLE public.microareas (
  id            TEXT    PRIMARY KEY,                          -- CUID
  name          TEXT    NOT NULL UNIQUE,
  code          TEXT    NOT NULL UNIQUE,
  macroarea     TEXT    NOT NULL,                             -- parent macro-area name
  description   TEXT    NOT NULL,
  color         TEXT    NOT NULL DEFAULT '#3b82f6',
  "order"       INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.3  elements
-- ---------------------------------------------------------------------------
-- Specific competency elements within a microarea.

CREATE TABLE public.elements (
  id            TEXT    PRIMARY KEY,                          -- CUID
  code          TEXT    NOT NULL UNIQUE,
  name          TEXT    NOT NULL,
  description   TEXT    NOT NULL,
  skill_level   TEXT    NOT NULL DEFAULT 'compreensão',
  microarea_id  TEXT    NOT NULL REFERENCES public.microareas(id) ON DELETE CASCADE,
  "order"       INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.4  questions
-- ---------------------------------------------------------------------------
-- The question bank. Questions authored by professors go through a lifecycle
-- of draft → test → validation → active.

CREATE TABLE public.questions (
  id              TEXT    PRIMARY KEY,                        -- CUID
  code            TEXT    NOT NULL UNIQUE,
  type            TEXT    NOT NULL DEFAULT 'OBJETIVA'
                  CHECK (type IN ('OBJETIVA', 'DISSERTATIVA')),
  statement       TEXT    NOT NULL,
  context         TEXT,                                      -- optional context block
  correct_answer  TEXT    NOT NULL,
  explanation     TEXT,                                      -- post-answer explanation
  difficulty      TEXT    NOT NULL DEFAULT 'médio',

  -- TRI (Item Response Theory) parameters
  tri_a           FLOAT,
  tri_b           FLOAT,
  tri_c           FLOAT,
  tri_calibrated  BOOLEAN NOT NULL DEFAULT false,

  -- Provenance
  source          TEXT    NOT NULL DEFAULT 'elaborada',
  source_year     INTEGER,                                   -- e.g. 2023 ENADE
  enade_id        TEXT,                                      -- original ENADE question ID

  -- Relations
  microarea_id    TEXT    NOT NULL REFERENCES public.microareas(id),
  element_id      TEXT    REFERENCES public.elements(id),
  author_id       TEXT    REFERENCES public.users(id),
  validator_id    TEXT    REFERENCES public.users(id),

  status          TEXT    NOT NULL DEFAULT 'RASCUNHO'
                  CHECK (status IN (
                    'RASCUNHO',
                    'AGUARDANDO_TESTE',
                    'EM_TESTE',
                    'AGUARDANDO_VALIDACAO',
                    'APROVADA',
                    'REPROVADA',
                    'ATIVA',
                    'INATIVA'
                  )),

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.5  alternatives
-- ---------------------------------------------------------------------------
-- Multiple-choice options for OBJETIVA questions.

CREATE TABLE public.alternatives (
  id            TEXT    PRIMARY KEY,                        -- CUID
  letter        TEXT    NOT NULL,                           -- A, B, C, D, E
  text          TEXT    NOT NULL,
  question_id   TEXT    NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.6  simulados
-- ---------------------------------------------------------------------------
-- Exam simulations (practice tests). Different types serve different purposes.

CREATE TABLE public.simulados (
  id            TEXT    PRIMARY KEY,                        -- CUID
  title         TEXT    NOT NULL,
  description   TEXT,
  type          TEXT    NOT NULL DEFAULT 'LIVRE'
                CHECK (type IN (
                  'DIAGNOSTICO',
                  'MICROAREA',
                  'MACROAREA',
                  'GERAL',
                  'LIVRE',
                  'ENADE_SIMULADO'
                )),
  phase         INTEGER,                                   -- associated phase (1-4)
  time_limit    INTEGER,                                   -- seconds; NULL = no limit
  question_count INTEGER NOT NULL DEFAULT 10,
  active        BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.7  simulado_configs
-- ---------------------------------------------------------------------------
-- Junction table linking questions to simulados with ordering.

CREATE TABLE public.simulado_configs (
  id            TEXT    PRIMARY KEY,                        -- CUID
  simulado_id   TEXT    NOT NULL REFERENCES public.simulados(id) ON DELETE CASCADE,
  question_id   TEXT    NOT NULL REFERENCES public.questions(id),
  "order"       INTEGER NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- 2.8  student_responses
-- ---------------------------------------------------------------------------
-- Records answers to database-stored questions (inside simulados or practice).
-- Scoped by `instance` for multi-tenant isolation.

CREATE TABLE public.student_responses (
  id            TEXT    PRIMARY KEY,                        -- CUID
  instance      TEXT    NOT NULL DEFAULT 'ENADIA',
  user_id       TEXT    NOT NULL REFERENCES public.users(id),
  question_id   TEXT    NOT NULL REFERENCES public.questions(id),
  simulado_id   TEXT    REFERENCES public.simulados(id),
  answer        TEXT    NOT NULL,
  is_correct    BOOLEAN,
  response_time INTEGER,                                   -- milliseconds
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.9  local_question_responses  ★ CRITICAL TABLE ★
-- ---------------------------------------------------------------------------
-- Tracks student responses to questions that exist ONLY in the client-side
-- in-memory question bank (enade-full-bank.ts). These questions do NOT have
-- a row in the `questions` table — their source data lives entirely on the
-- client and is baked into the build.
--
-- The `question_bank_id` field stores the ID as it appears in the in-memory
-- bank, allowing the app to correlate responses back to the correct question.
-- Topic and macroarea are denormalised here so analytics can be computed
-- without joining to any question table.

CREATE TABLE public.local_question_responses (
  id              TEXT    PRIMARY KEY,                      -- CUID
  instance        TEXT    NOT NULL DEFAULT 'ENADIA',
  user_id         TEXT    NOT NULL REFERENCES public.users(id),
  question_bank_id TEXT   NOT NULL,                         -- ID from in-memory bank
  topic           TEXT    NOT NULL,                         -- microarea name (denormalised)
  macroarea       TEXT    NOT NULL,                         -- macroarea name (denormalised)
  difficulty      TEXT,                                    -- question difficulty level
  answer          TEXT    NOT NULL,                         -- student's answer
  correct_answer  TEXT    NOT NULL,                         -- expected correct answer
  is_correct      BOOLEAN NOT NULL,
  response_time   INTEGER,                                 -- milliseconds
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.10 essay_answers
-- ---------------------------------------------------------------------------
-- Stores essay (dissertativa) submissions and AI-generated feedback.
-- Scoped by `instance` for multi-tenant isolation.

CREATE TABLE public.essay_answers (
  id            TEXT    PRIMARY KEY,                        -- CUID
  instance      TEXT    NOT NULL DEFAULT 'ENADIA',
  user_id       TEXT    NOT NULL REFERENCES public.users(id),
  question_id   TEXT    NOT NULL REFERENCES public.questions(id),
  simulado_id   TEXT    REFERENCES public.simulados(id),
  answer        TEXT    NOT NULL,                           -- student's essay text
  ai_feedback   TEXT,                                      -- AI-generated feedback
  ai_score      FLOAT,                                     -- 0-100 score from AI
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2.11 question_tags
-- ---------------------------------------------------------------------------
-- Free-form tags for categorising questions beyond microarea/element.

CREATE TABLE public.question_tags (
  id            TEXT    PRIMARY KEY,                        -- CUID
  name          TEXT    NOT NULL,
  question_id   TEXT    NOT NULL REFERENCES public.questions(id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- 2.12 system_configs
-- ---------------------------------------------------------------------------
-- Key-value store for platform-wide configuration.

CREATE TABLE public.system_configs (
  id            TEXT    PRIMARY KEY,                        -- CUID
  key           TEXT    NOT NULL UNIQUE,
  value         TEXT    NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================================
-- SECTION 3: INDEXES
-- ============================================================================
-- Performance-critical indexes. Composite indexes are ordered so the most
-- selective / commonly filtered column comes first.

-- 3.1  users
CREATE INDEX  idx_users_instance        ON public.users(instance);
CREATE INDEX  idx_users_email           ON public.users(email);
CREATE INDEX  idx_users_role            ON public.users(role);
CREATE INDEX  idx_users_active          ON public.users(active);
CREATE INDEX  idx_users_instance_role   ON public.users(instance, role);

-- 3.2  elements
CREATE INDEX  idx_elements_microarea    ON public.elements(microarea_id);

-- 3.3  questions
CREATE INDEX  idx_questions_microarea   ON public.questions(microarea_id);
CREATE INDEX  idx_questions_element     ON public.questions(element_id);
CREATE INDEX  idx_questions_author      ON public.questions(author_id);
CREATE INDEX  idx_questions_validator   ON public.questions(validator_id);
CREATE INDEX  idx_questions_status      ON public.questions(status);
CREATE INDEX  idx_questions_type        ON public.questions(type);

-- 3.4  alternatives
CREATE INDEX  idx_alternatives_question  ON public.alternatives(question_id);

-- 3.5  simulado_configs
CREATE INDEX  idx_simulado_configs_sim  ON public.simulado_configs(simulado_id);
CREATE INDEX  idx_simulado_configs_qst  ON public.simulado_configs(question_id);

-- 3.6  student_responses
CREATE INDEX  idx_student_responses_instance  ON public.student_responses(instance);
CREATE INDEX  idx_student_responses_user     ON public.student_responses(user_id);
CREATE INDEX  idx_student_responses_question ON public.student_responses(question_id);
CREATE INDEX  idx_student_responses_simulado ON public.student_responses(simulado_id);
CREATE INDEX  idx_student_responses_user_sim  ON public.student_responses(user_id, simulado_id);

-- 3.7  local_question_responses
CREATE INDEX  idx_local_qr_instance      ON public.local_question_responses(instance);
CREATE INDEX  idx_local_qr_user         ON public.local_question_responses(user_id);
CREATE INDEX  idx_local_qr_topic        ON public.local_question_responses(topic);
CREATE INDEX  idx_local_qr_macroarea    ON public.local_question_responses(macroarea);
CREATE INDEX  idx_local_qr_user_topic   ON public.local_question_responses(user_id, topic);

-- 3.8  essay_answers
CREATE INDEX  idx_essay_answers_instance ON public.essay_answers(instance);
CREATE INDEX  idx_essay_answers_user     ON public.essay_answers(user_id);
CREATE INDEX  idx_essay_answers_question ON public.essay_answers(question_id);
CREATE INDEX  idx_essay_answers_simulado ON public.essay_answers(simulado_id);

-- 3.9  question_tags
CREATE INDEX  idx_question_tags_question ON public.question_tags(question_id);
CREATE INDEX  idx_question_tags_name     ON public.question_tags(name);


-- ============================================================================
-- SECTION 4: TRIGGERS
-- ============================================================================
-- Auto-update `updated_at` on every row modification for tables that have it.

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();

CREATE TRIGGER trg_questions_updated_at
  BEFORE UPDATE ON public.questions
  FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();

CREATE TRIGGER trg_simulados_updated_at
  BEFORE UPDATE ON public.simulados
  FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();

CREATE TRIGGER trg_system_configs_updated_at
  BEFORE UPDATE ON public.system_configs
  FOR EACH ROW EXECUTE FUNCTION public.trigger_set_updated_at();


-- ============================================================================
-- SECTION 5: VIEWS
-- ============================================================================
-- Pre-computed analytical views for dashboards and reports.

-- ---------------------------------------------------------------------------
-- 5.1  student_ranking
-- ---------------------------------------------------------------------------
-- Aggregated ranking view combining responses from both database questions
-- (student_responses) and in-memory bank questions (local_question_responses).

CREATE OR REPLACE VIEW public.student_ranking AS
SELECT
  u.id            AS user_id,
  u.instance      AS instance,
  u.name,
  u.email,
  u.ra,
  u.curso,
  u.periodo,
  u.modalidade,

  -- DB question responses
  COUNT(sr.id)    AS db_total_answered,
  COUNT(sr.id) FILTER (WHERE sr.is_correct = true) AS db_total_correct,

  -- Local bank question responses
  COUNT(lqr.id)  AS local_total_answered,
  COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true) AS local_total_correct,

  -- Combined totals
  (COALESCE(COUNT(sr.id), 0) + COALESCE(COUNT(lqr.id), 0)) AS total_answered,
  (COALESCE(COUNT(sr.id) FILTER (WHERE sr.is_correct = true), 0)
   + COALESCE(COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true), 0)) AS total_correct,

  CASE
    WHEN (COALESCE(COUNT(sr.id), 0) + COALESCE(COUNT(lqr.id), 0)) > 0
    THEN ROUND(
      (COALESCE(COUNT(sr.id) FILTER (WHERE sr.is_correct = true), 0)
       + COALESCE(COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true), 0))
      ::FLOAT
      / (COALESCE(COUNT(sr.id), 0) + COALESCE(COUNT(lqr.id), 0))::FLOAT
      * 100
    )
    ELSE 0
  END AS hit_rate,

  CASE
    WHEN AVG(sr.response_time) IS NOT NULL OR AVG(lqr.response_time) IS NOT NULL
    THEN ROUND(
      COALESCE(AVG(sr.response_time), 0)
      + COALESCE(AVG(lqr.response_time), 0)
    )
    ELSE NULL
  END AS avg_response_time,

  RANK() OVER (
    PARTITION BY u.instance
    ORDER BY
      CASE
        WHEN (COALESCE(COUNT(sr.id), 0) + COALESCE(COUNT(lqr.id), 0)) > 0
        THEN ROUND(
          (COALESCE(COUNT(sr.id) FILTER (WHERE sr.is_correct = true), 0)
           + COALESCE(COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true), 0))
          ::FLOAT
          / (COALESCE(COUNT(sr.id), 0) + COALESCE(COUNT(lqr.id), 0))::FLOAT
          * 100
        )
        ELSE 0
      END DESC,
      (COALESCE(COUNT(sr.id) FILTER (WHERE sr.is_correct = true), 0)
       + COALESCE(COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true), 0)) DESC
  ) AS position

FROM public.users u
LEFT JOIN public.student_responses sr        ON sr.user_id = u.id AND sr.instance = u.instance
LEFT JOIN public.local_question_responses lqr ON lqr.user_id = u.id AND lqr.instance = u.instance
WHERE u.role = 'ALUNO' AND u.active = true
GROUP BY u.id, u.instance, u.name, u.email, u.ra, u.curso, u.periodo, u.modalidade;

-- ---------------------------------------------------------------------------
-- 5.2  class_performance
-- ---------------------------------------------------------------------------
-- Per-class / per-course performance aggregation.

CREATE OR REPLACE VIEW public.class_performance AS
SELECT
  u.instance,
  u.curso,
  u.periodo,
  u.modalidade,
  COUNT(DISTINCT u.id) AS total_students,
  AVG(
    CASE WHEN (sr_count + lqr_count) > 0
      THEN ROUND(((sr_correct + lqr_correct)::FLOAT / (sr_count + lqr_count)::FLOAT) * 100)
      ELSE 0
    END
  ) AS avg_hit_rate
FROM public.users u
LEFT JOIN LATERAL (
  SELECT
    COUNT(sr.id)   AS sr_count,
    COUNT(sr.id) FILTER (WHERE sr.is_correct = true) AS sr_correct
  FROM public.student_responses sr
  WHERE sr.user_id = u.id AND sr.instance = u.instance
) sub_sr ON true
LEFT JOIN LATERAL (
  SELECT
    COUNT(lqr.id)  AS lqr_count,
    COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true) AS lqr_correct
  FROM public.local_question_responses lqr
  WHERE lqr.user_id = u.id AND lqr.instance = u.instance
) sub_lqr ON true
WHERE u.role = 'ALUNO' AND u.active = true
GROUP BY u.instance, u.curso, u.periodo, u.modalidade;

-- ---------------------------------------------------------------------------
-- 5.3  microarea_performance
-- ---------------------------------------------------------------------------
-- Per-microarea hit-rate analytics (local bank responses only, since those
-- are the primary source of topic-level data).

CREATE OR REPLACE VIEW public.microarea_performance AS
SELECT
  lqr.instance,
  lqr.topic       AS microarea_name,
  lqr.macroarea,
  COUNT(lqr.id)   AS total_answered,
  COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true) AS total_correct,
  CASE
    WHEN COUNT(lqr.id) > 0
    THEN ROUND((COUNT(lqr.id) FILTER (WHERE lqr.is_correct = true)::FLOAT / COUNT(lqr.id)::FLOAT) * 100)
    ELSE 0
  END AS hit_rate,
  ROUND(AVG(lqr.response_time)) AS avg_response_time
FROM public.local_question_responses lqr
GROUP BY lqr.instance, lqr.topic, lqr.macroarea;


-- ============================================================================
-- SECTION 6: SEED DATA
-- ============================================================================

-- (Commented out — insert via application seed script or manually as needed)
--
-- INSERT INTO public.system_configs (id, key, value) VALUES
--   ('cuid_here', 'CURRENT_PHASE', '1');
