import { PrismaClient, QuestionStatus } from '@prisma/client';

const prisma = new PrismaClient();

// ─── MICROAREA CODE → TOPIC NAME MAPPING ───────────────────────
const TOPIC_TO_CODE: Record<string, string> = {
  'Lógica Proposicional': 'LOG',
  'Matemática Discreta': 'MAT',
  'Autômatos e Linguagens Formais': 'AUT',
  'Programação Orientada a Objetos': 'POO',
  'Algoritmos e Estruturas de Dados': 'ALG',
  'Banco de Dados': 'BD',
  'Engenharia de Software': 'ES',
  'Sistemas Operacionais': 'SO',
  'Redes': 'RED',
  'Redes de Computadores': 'RED',
  'Sistemas Distribuídos': 'SD',
  'Criptografia': 'CRI',
  'Inteligência Artificial': 'IA',
  'Ciência de Dados': 'CD',
  'Ética Profissional': 'ETI',
  'Legislação': 'LEG',
};

// ─── TRI PARAMS BY DIFFICULTY ──────────────────────────────────
function getTRI(difficulty: string) {
  if (difficulty === 'fácil') return { a: 0.8, b: -1.2, c: 0.15 };
  if (difficulty === 'difícil') return { a: 1.3, b: 1.2, c: 0.25 };
  return { a: 1.0, b: 0.0, c: 0.2 }; // médio
}

// ─── ALL QUESTIONS (consolidated from batch files) ──────────────
interface Q {
  id: string; topic: string; macroarea: string; element: string;
  difficulty: string; statement: string;
  alternatives: { letter: string; text: string }[];
  correctAnswer: string; explanation: string;
}

// Batch 1: LOG (10), MAT (10), AUT (10), ALG (10), POO (10)
const batch1: Q[] = [
  // ===== LÓGICA PROPOSICIONAL (10) =====
  { id:"logica_conectivos_001", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Conectivos lógicos", difficulty:"fácil", statement:"Em um sistema de verificação de segurança de uma aplicação bancária, o acesso é concedido quando o usuário fornece a senha correta (P) e o dispositivo de dois fatores está ativo (Q). Qual expressão representa a condição de acesso permitido usando o conectivo AND?", alternatives:[{letter:"A",text:"P ∨ Q"},{letter:"B",text:"P ∧ Q"},{letter:"C",text:"¬P → Q"},{letter:"D",text:"P ⊕ Q"},{letter:"E",text:"Q → P"}], correctAnswer:"B", explanation:"O conectivo lógico AND (∧) resulta em verdadeiro apenas quando ambas as proposições são verdadeiras." },
  { id:"logica_tabelaverdade_002", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Tabela-verdade", difficulty:"médio", statement:"Um engenheiro de software precisa validar a expressão lógica (P → Q) ∧ (Q → R). Quantas linhas são necessárias na tabela-verdade dessa expressão?", alternatives:[{letter:"A",text:"4 linhas"},{letter:"B",text:"6 linhas"},{letter:"C",text:"8 linhas"},{letter:"D",text:"9 linhas"},{letter:"E",text:"12 linhas"}], correctAnswer:"C", explanation:"Com 3 variáveis, o número de linhas é 2³ = 8." },
  { id:"logica_tautologia_003", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Tautologia", difficulty:"médio", statement:"Considere a proposição (P → Q) ↔ (¬Q → ¬P). Classifique essa proposição.", alternatives:[{letter:"A",text:"É uma contradição"},{letter:"B",text:"É uma contingência"},{letter:"C",text:"É uma tautologia, pois equivale à contrapositiva"},{letter:"D",text:"É uma contradição, pois a contrapositiva tem valor oposto"},{letter:"E",text:"É uma contingência, pois a bicondicional nunca é satisfeita"}], correctAnswer:"C", explanation:"P → Q é logicamente equivalente à sua contrapositiva ¬Q → ¬P, logo a bicondicional é sempre verdadeira." },
  { id:"logica_equivalencia_004", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Equivalência lógica", difficulty:"médio", statement:"A regra 'se o campo é obrigatório, então o usuário não é menor de idade' com M='menor de idade' e O='obrigatório'. Qual expressão é a tradução direta?", alternatives:[{letter:"A",text:"¬O → M"},{letter:"B",text:"M → ¬O"},{letter:"C",text:"¬M ∨ ¬O"},{letter:"D",text:"O → ¬M"},{letter:"E",text:"O ∧ ¬M"}], correctAnswer:"D", explanation:"A tradução direta de 'se O então não M' é O → ¬M." },
  { id:"logica_implicacao_005", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Implicação", difficulty:"difícil", statement:"Premissas: P1(S→B), P2(B→U), P3(¬U). Aplicando modus tollens, qual conclusão é válida?", alternatives:[{letter:"A",text:"S está em produção e backups atualizados"},{letter:"B",text:"BD sincronizado, mas sistema não em produção"},{letter:"C",text:"Sistema não em produção E BD não sincronizado"},{letter:"D",text:"BD sincronizado e backups atualizados"},{letter:"E",text:"Não é possível concluir nada"}], correctAnswer:"C", explanation:"De P2 e P3: ¬B. De P1 e ¬B: ¬S. Conclusão: ¬S ∧ ¬B." },
  { id:"logica_argumento_006", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Argumento válido", difficulty:"médio", statement:"Se login falha 3x, conta é bloqueada. Conta foi bloqueada. Logo, login falhou 3x. Esse argumento é válido?", alternatives:[{letter:"A",text:"Válido, usa modus ponens"},{letter:"B",text:"Válido, consequência possível"},{letter:"C",text:"Inválido, falácia da afirmação do consequente"},{letter:"D",text:"Inválido, modus tollens incorreto"},{letter:"E",text:"Válido, necessariamente login falhou 3x"}], correctAnswer:"C", explanation:"Estrutura P→Q, Q, logo P é a falácia da afirmação do consequente." },
  { id:"logica_formasnormais_007", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Formas normais", difficulty:"difícil", statement:"Converter (P → Q) ∧ (R → S) para Forma Normal Conjuntiva. Qual é a FNC correta?", alternatives:[{letter:"A",text:"(P ∧ Q) ∧ (R ∧ S)"},{letter:"B",text:"(¬P ∨ Q) ∧ (¬R ∨ S)"},{letter:"C",text:"(P ∨ ¬Q) ∧ (R ∨ ¬S)"},{letter:"D",text:"(¬P ∧ Q) ∨ (¬R ∧ S)"},{letter:"E",text:"Já está na FNC"}], correctAnswer:"B", explanation:"P → Q ≡ ¬P ∨ Q. Portanto (¬P ∨ Q) ∧ (¬R ∨ S) é a FNC." },
  { id:"logica_inferencia_008", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Inferência", difficulty:"médio", statement:"Regras: Se febre(F) então infecção(I). Se infecção(I) e fadiga(D), repouso(R). F e D são verdadeiros. Qual conclusão?", alternatives:[{letter:"A",text:"Há infecção, sem repouso"},{letter:"B",text:"É necessário repouso"},{letter:"C",text:"Paciente não tem febre"},{letter:"D",text:"Há infecção e é necessário repouso"},{letter:"E",text:"Apenas infecção"}], correctAnswer:"D", explanation:"F verdadeiro + F→I = I. I + D = I∧D verdadeiro + I∧D→R = R. Conclusão: I ∧ R." },
  { id:"logica_formasraciocinio_009", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Formas de raciocínio", difficulty:"fácil", statement:"Função que retorna verdadeiro se pelo menos uma de A, B ou C for verdadeira. Qual conectivo?", alternatives:[{letter:"A",text:"A ∧ B ∧ C"},{letter:"B",text:"A ∨ B ∨ C"},{letter:"C",text:"¬(A ∧ B ∧ C)"},{letter:"D",text:"A → (B ∨ C)"},{letter:"E",text:"(A ⊕ B) ⊕ C"}], correctAnswer:"B", explanation:"A disjunção (∨) resulta em verdadeiro quando pelo menos um operando é verdadeiro." },
  { id:"logica_argumentoestrutura_010", topic:"Lógica Proposicional", macroarea:"Fundamentos", element:"Argumento válido", difficulty:"difícil", statement:"P1:O→R, P2:R∧P→A, P3:O∧P. Qual conclusão válida completa?", alternatives:[{letter:"A",text:"Apenas A (aplicação funciona)"},{letter:"B",text:"Apenas R (BD responde)"},{letter:"C",text:"R e A (BD responde E aplicação funciona)"},{letter:"D",text:"Não é possível concluir A"},{letter:"E",text:"Apenas O e P são garantidos"}], correctAnswer:"C", explanation:"De P3: O=V, P=V. De P1+O: R=V. De P2+R+P: A=V. Conclusão: R ∧ A." },

  // ===== MATEMÁTICA DISCRETA (10) =====
  { id:"disc_conjuntos_001", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Conjuntos e operações", difficulty:"fácil", statement:"A={1,2,3,4,5}, B={3,4,5,6,7}. Qual operação identifica os com AMBAS as permissões?", alternatives:[{letter:"A",text:"A ∪ B = {1,2,3,4,5,6,7}"},{letter:"B",text:"A ∩ B = {3,4,5}"},{letter:"C",text:"A − B = {1,2}"},{letter:"D",text:"B − A = {6,7}"},{letter:"E",text:"A △ B = {1,2,6,7}"}], correctAnswer:"B", explanation:"A interseção retorna elementos comuns a ambos os conjuntos." },
  { id:"disc_relacoesfuncoes_002", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Relações e funções", difficulty:"médio", statement:"Relação R sobre A={1,2,3,4}: xRy se x|y. Classifique R quanto à reflexividade, simetria, antissimetria e transitividade.", alternatives:[{letter:"A",text:"Reflexiva, simétrica e transitiva"},{letter:"B",text:"Reflexiva, antissimétrica e transitiva, não simétrica"},{letter:"C",text:"Não reflexiva, simétrica, antissimétrica e transitiva"},{letter:"D",text:"Reflexiva, simétrica e antissimétrica"},{letter:"E",text:"Reflexiva, não antissimétrica e não transitiva"}], correctAnswer:"B", explanation:"'Divide' é reflexiva (x|x), antissimétrica (se x|y e y|x, x=y) e transitiva, mas não simétrica (2|4 mas 4∤2)." },
  { id:"disc_inducao_003", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Indução matemática", difficulty:"difícil", statement:"Provar que 1+3+5+...+(2n-1)=n². Na etapa indutiva, supondo válida para n=k, qual expressão deve ser demonstrada para n=k+1?", alternatives:[{letter:"A",text:"1+3+5+...+(2k+1)=(k+1)²"},{letter:"B",text:"1+3+5+...+(2k-1)+1=(k+1)²"},{letter:"C",text:"1+3+5+...+(2k+1)=k²+2k"},{letter:"D",text:"1+3+5+...+(2k-1)=(k+1)²"},{letter:"E",text:"1+3+5+...+(2k-1)+2k=(k+1)²"}], correctAnswer:"A", explanation:"O último termo para n=k+1 é 2(k+1)-1=2k+1. Deve-se mostrar Σ(2i-1)=(k+1)²." },
  { id:"disc_combinatoria_004", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Combinatória", difficulty:"médio", statement:"Senhas de 6 caracteres com exatamente 4 letras maiúsculas e 2 dígitos. Quantas senhas?", alternatives:[{letter:"A",text:"26⁴ × 10²"},{letter:"B",text:"C(6,4) × 26⁴ × 10² × 4! × 2!"},{letter:"C",text:"C(6,4) × 26⁴ × 10²"},{letter:"D",text:"36⁶"},{letter:"E",text:"P(6,4) × 26⁴ × 10²"}], correctAnswer:"C", explanation:"C(6,4) posições para letras × 26⁴ para letras × 10² para dígitos." },
  { id:"disc_grafos_005", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Grafos", difficulty:"médio", statement:"Grafo não direcionado com 5 vértices e 7 arestas. Qual afirmativa é necessariamente verdadeira?", alternatives:[{letter:"A",text:"O grafo é planar"},{letter:"B",text:"Todos os vértices têm grau par"},{letter:"C",text:"A soma dos graus é 14 (Lema do Aperto de Mão)"},{letter:"D",text:"O grafo possui exatamente 5 ciclos"},{letter:"E",text:"O grafo é necessariamente conexo"}], correctAnswer:"C", explanation:"Pelo Handshaking Lemma: Σgraus = 2×|E| = 2×7 = 14." },
  { id:"disc_arvores_006", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Árvores", difficulty:"fácil", statement:"Árvore geradora conectando 8 computadores sem ciclos. Mínimo de conexões necessárias?", alternatives:[{letter:"A",text:"6"},{letter:"B",text:"7"},{letter:"C",text:"8"},{letter:"D",text:"9"},{letter:"E",text:"10"}], correctAnswer:"B", explanation:"Árvore com n vértices tem n-1 arestas: 8-1=7." },
  { id:"disc_teorianumeros_007", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Teoria dos números", difficulty:"médio", statement:"MDC(252, 198) pelo algoritmo de Euclides?", alternatives:[{letter:"A",text:"12"},{letter:"B",text:"18"},{letter:"C",text:"6"},{letter:"D",text:"9"},{letter:"E",text:"36"}], correctAnswer:"B", explanation:"252=198×1+54, 198=54×3+36, 54=36×1+18, 36=18×2+0. MDC=18." },
  { id:"disc_progressoes_008", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Progressões", difficulty:"fácil", statement:"Backup cresce 500MB/dia, primeiro=2GB. Total acumulado após 10 dias?", alternatives:[{letter:"A",text:"42,5 GB"},{letter:"B",text:"45,0 GB"},{letter:"C",text:"47,5 GB"},{letter:"D",text:"50,0 GB"},{letter:"E",text:"52,5 GB"}], correctAnswer:"A", explanation:"PA: a₁=2, r=0,5. S₁₀=10×(2+6,5)/2=42,5 GB." },
  { id:"disc_probabilidade_009", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Probabilidade", difficulty:"médio", statement:"IDS com 95% verdadeiros positivos, 3% falsos positivos. Probabilidade de ataque real=1%. Probabilidade de que alerta seja ataque real?", alternatives:[{letter:"A",text:"95%"},{letter:"B",text:"92%"},{letter:"C",text:"24%"},{letter:"D",text:"50%"},{letter:"E",text:"1%"}], correctAnswer:"C", explanation:"Bayes: P(Ataque|Alerta) = 0,95×0,01 / (0,95×0,01+0,03×0,99) ≈ 0,24 = 24%." },
  { id:"disc_matrizes_010", topic:"Matemática Discreta", macroarea:"Fundamentos", element:"Matrizes", difficulty:"difícil", statement:"Matriz de adjacência A (4×4). O que A²[i][j] representa?", alternatives:[{letter:"A",text:"Vezes que usuário i e j compraram o mesmo produto"},{letter:"B",text:"Número de produtos comprados por ambos i e j"},{letter:"C",text:"Total de compras de i"},{letter:"D",text:"Probabilidade de i comprar j"},{letter:"E",text:"Usuários que compraram j"}], correctAnswer:"B", explanation:"A²[i][j]=ΣA[i][k]×A[k][j], conta produtos comuns entre i e j." },

  // ===== AUTÔMATOS E LINGUAGENS FORMAIS (10) =====
  { id:"autom_afd_001", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"AFD", difficulty:"médio", statement:"AFD para reconhecer strings binárias terminando em '01'. Número mínimo de estados?", alternatives:[{letter:"A",text:"2"},{letter:"B",text:"3"},{letter:"C",text:"4"},{letter:"D",text:"5"},{letter:"E",text:"6"}], correctAnswer:"B", explanation:"Precisamos rastrear: nada relevante, último foi 0, terminou com 01 = 3 estados." },
  { id:"autom_afnd_002", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"AFND", difficulty:"médio", statement:"AFND com transição não determinística de q0 com 'a' para {q0,q1}, q1 com 'b' para q2. String 'aab'?", alternatives:[{letter:"A",text:"Apenas q₀→q₁→q₂ (aceita)"},{letter:"B",text:"Caminho q₀→q₀→q₁→q₂ (aceita) entre outros"},{letter:"C",text:"q₀→q₀→q₀ (rejeita) e q₀→q₁→q₂ (aceita)"},{letter:"D",text:"Apenas q₀→q₀→q₁→q₂"},{letter:"E",text:"Três caminhos, um aceita"}], correctAnswer:"B", explanation:"O AFND explora todas as transições. q₀→q₀→q₁→q₂ é um caminho aceito." },
  { id:"autom_exprege_003", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Expressões regulares", difficulty:"fácil", statement:"Expressão regular para senhas com letras minúsculas e dígitos, 6 a 10 caracteres?", alternatives:[{letter:"A",text:"[a-z0-9]{6,10}"},{letter:"B",text:"[a-zA-Z0-9]{6,10}"},{letter:"C",text:"[a-z0-9]{6}"},{letter:"D",text:"[a-z0-9]{10}"},{letter:"E",text:"^[a-z][0-9]{5,9}$"}], correctAnswer:"A", explanation:"[a-z0-9] define charset, {6,10} define comprimento entre 6 e 10." },
  { id:"autom_linguagensreg_004", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Linguagens regulares", difficulty:"médio", statement:"L₁={w|w contém '010'}, L₂={w|#0s=#1s}. Sobre classificação?", alternatives:[{letter:"A",text:"Ambas regulares"},{letter:"B",text:"L₁ regular, L₂ não regular (requer contagem ilimitada)"},{letter:"C",text:"L₁ não regular, L₂ regular"},{letter:"D",text:"L₁ livre de contexto, L₂ regular"},{letter:"E",text:"Nenhuma regular"}], correctAnswer:"B", explanation:"L₁ é regular (substring finito). L₂ não é regular (Lema do Bombeamento). L₂ é livre de contexto." },
  { id:"autom_gramaticas_005", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Gramáticas regulares", difficulty:"fácil", statement:"Gramática regular para {aⁿb | n≥1}?", alternatives:[{letter:"A",text:"S → aS | b"},{letter:"B",text:"S → aS | ab"},{letter:"C",text:"S → Sa | b"},{letter:"D",text:"S → aSb | ε"},{letter:"E",text:"S → aA, A → aA | b"}], correctAnswer:"B", explanation:"S→aS|ab gera ab, aab, aaab... linear à direita." },
  { id:"autom_pilha_006", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Autômato de pilha", difficulty:"difícil", statement:"L={wwᴿ | w∈{0,1}*}. Sobre reconhecimento?", alternatives:[{letter:"A",text:"APD pode reconhecer deterministicamente"},{letter:"B",text:"Não é livre de contexto"},{letter:"C",text:"Livre de contexto, APND reconhece mas não APD (sem marcador)"},{letter:"D",text:"APD com dois marcadores resolve"},{letter:"E",text:"É regular"}], correctAnswer:"C", explanation:"L é livre de contexto não determinística mas não determinística." },
  { id:"autom_turing_007", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Máquina de Turing", difficulty:"médio", statement:"MT para computar f(n)=n+1 em unário. Algoritmo?", alternatives:[{letter:"A",text:"Mover direita até espaço, escrever 1, parar"},{letter:"B",text:"Apagar primeiro 1, mover direita, escrever 1"},{letter:"C",text:"Contar todos 1s, mover e escrever contagem+1"},{letter:"D",text:"Substituir último 1 por dois 1s"},{letter:"E",text:"Mover esquerda, escrever 1"}], correctAnswer:"A", explanation:"Em unário, mover até o primeiro branco e escrever 1 resulta em n+1." },
  { id:"autom_chomsky_008", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Hierarquia de Chomsky", difficulty:"médio", statement:"Sobre a Hierarquia de Chomsky, qual afirmação está correta?", alternatives:[{letter:"A",text:"Tipo 3 ⊂ Tipo 2 ⊂ Tipo 1 ⊂ Tipo 0"},{letter:"B",text:"Tipo 0 ⊂ Tipo 1 ⊂ Tipo 2 ⊂ Tipo 3"},{letter:"C",text:"Todas as classes são equivalentes em poder expressivo"},{letter:"D",text:"Apenas Tipo 0 e Tipo 3 existem"},{letter:"E",text:"Tipo 2 é mais restrito que Tipo 1"}], correctAnswer:"A", explanation:"A hierarquia vai: Regular(T3) ⊂ Livre de Contexto(T2) ⊂ Sensível ao Contexto(T1) ⊂ Irrestrita(T0)." },
  { id:"autom_decidibilidade_009", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Decidibilidade", difficulty:"difícil", statement:"O problema da parada é indecidível. Qual técnica demonstra isso?", alternatives:[{letter:"A",text:"Indução matemática"},{letter:"B",text:"Diagonalização de Cantor (argumento de Turing)"},{letter:"C",text:"Programação dinâmica"},{letter:"D",text:"Lema do Bombeamento"},{letter:"E",text:"Algoritmo de Euclides"}], correctAnswer:"B", explanation:"Turing usou diagonalização para provar que não existe máquina universal que decida a parada." },
  { id:"autom_minimizacao_010", topic:"Autômatos e Linguagens Formais", macroarea:"Teoria", element:"Minimização de AFD", difficulty:"médio", statement:"Sobre minimização de AFD, qual afirmação está correta?", alternatives:[{letter:"A",text:"O AFD minimizado sempre tem mais estados que o original"},{letter:"B",text:"A minimização remove estados equivalentes, mantendo a linguagem"},{letter:"C",text:"Dois AFDs para a mesma linguagem podem ter diferentes mínimos"},{letter:"D",text:"A minimização muda a linguagem reconhecida"},{letter:"E",text:"Todo AFD já é minimal"}], correctAnswer:"B", explanation:"Minimização agrupa estados equivalentes. O AFD mínimo é único para cada linguagem regular." },

  // ===== ALGORITMOS E ESTRUTURAS DE DADOS (10) =====
  { id:"alg_complexidade_001", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Complexidade", difficulty:"fácil", statement:"Qual notação representa o pior caso de tempo de execução de um algoritmo?", alternatives:[{letter:"A",text:"Big-O (O)"},{letter:"B",text:"Big-Omega (Ω)"},{letter:"C",text:"Big-Theta (Θ)"},{letter:"D",text:"Little-o (o)"},{letter:"E",text:"Little-omega (ω)"}], correctAnswer:"A", explanation:"Big-O representa o limitante superior assintótico (pior caso)." },
  { id:"alg_recursao_002", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Recursão", difficulty:"médio", statement:"Qual é a complexidade de tempo da recursão para Fibonacci sem memoização?", alternatives:[{letter:"A",text:"O(n)"},{letter:"B",text:"O(log n)"},{letter:"C",text:"O(φⁿ) ≈ O(2ⁿ)"},{letter:"D",text:"O(n²)"},{letter:"E",text:"O(n log n)"}], correctAnswer:"C", explanation:"Sem memoização, Fibonacci faz chamadas recursivas exponenciais ≈ O(1,618ⁿ)." },
  { id:"alg_busca_003", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Busca", difficulty:"fácil", statement:"Busca binária em array ordenado de 1000 elementos. Máximo de comparações?", alternatives:[{letter:"A",text:"1000"},{letter:"B",text:"500"},{letter:"C",text:"10"},{letter:"D",text:"100"},{letter:"E",text:"7"}], correctAnswer:"C", explanation:"Busca binária: ⌈log₂1000⌉ = ⌈9,97⌉ = 10 comparações no máximo." },
  { id:"alg_ordenacao_004", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Ordenação", difficulty:"médio", statement:"Qual algoritmo de ordenação tem complexidade O(n log n) no pior caso E é in-place?", alternatives:[{letter:"A",text:"QuickSort"},{letter:"B",text:"MergeSort"},{letter:"C",text:"HeapSort"},{letter:"D",text:"BubbleSort"},{letter:"E",text:"InsertionSort"}], correctAnswer:"C", explanation:"HeapSort é O(n log n) em todos os casos e opera in-place (O(1) espaço extra)." },
  { id:"alg_listas_005", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Listas encadeadas", difficulty:"médio", statement:"Vantagem da lista duplamente encadeada sobre a simples?", alternatives:[{letter:"A",text:"Usa menos memória"},{letter:"B",text:"Permite remoção em O(1) dado o nó"},{letter:"C",text:"Acesso aleatório mais rápido"},{letter:"D",text:"Busca mais eficiente"},{letter:"E",text:"Menos overhead por nó"}], correctAnswer:"B", explanation:"Lista dupla permite navegar para trás, facilitando remoção O(1) com referência direta." },
  { id:"alg_pilhasfilas_006", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Pilhas e filas", difficulty:"fácil", statement:"Qual estrutura é ideal para verificar balanceamento de parênteses em expressões?", alternatives:[{letter:"A",text:"Fila"},{letter:"B",text:"Lista"},{letter:"C",text:"Pilha (LIFO)"},{letter:"D",text:"Árvore"},{letter:"E",text:"Heap"}], correctAnswer:"C", explanation:"Pilha permite desempilhar e verificar o par mais recente com LIFO." },
  { id:"alg_arvores_007", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Árvores BST", difficulty:"médio", statement:"BST com inserção na ordem: 50, 30, 70, 20, 40, 60, 80. Qual é a travessia em ordem?", alternatives:[{letter:"A",text:"50,30,20,40,70,60,80"},{letter:"B",text:"20,30,40,50,60,70,80"},{letter:"C",text:"80,70,60,50,40,30,20"},{letter:"D",text:"50,30,70,20,40,60,80"},{letter:"E",text:"20,40,30,60,80,70,50"}], correctAnswer:"B", explanation:"In-order traversal de BST sempre produz elementos em ordem crescente." },
  { id:"alg_grafos_008", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Grafos - BFS/DFS", difficulty:"médio", statement:"Para encontrar o menor caminho em grafo ponderado, qual algoritmo é mais adequado?", alternatives:[{letter:"A",text:"BFS"},{letter:"B",text:"DFS"},{letter:"C",text:"Dijkstra"},{letter:"D",text:"Kruskal"},{letter:"E",text:"Topological Sort"}], correctAnswer:"C", explanation:"Dijkstra encontra menor caminho em grafos ponderados com pesos positivos." },
  { id:"alg_progdinamica_009", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Programação dinâmica", difficulty:"difícil", statement:"Na PD, o problema da mochila 0/1 com n itens e capacidade W tem complexidade?", alternatives:[{letter:"A",text:"O(n)"},{letter:"B",text:"O(nW)"},{letter:"C",text:"O(2ⁿ)"},{letter:"D",text:"O(n log W)"},{letter:"E",text:"O(W²)"}], correctAnswer:"B", explanation:"A abordagem bottom-up com tabela n×W resulta em O(nW) tempo e espaço." },
  { id:"alg_guloso_010", topic:"Algoritmos e Estruturas de Dados", macroarea:"Algoritmos", element:"Algoritmos gulosos", difficulty:"médio", statement:"Qual problema NÃO é resolvido de forma ótima por algoritmo guloso?", alternatives:[{letter:"A",text:"Árvore Geradora Mínima (Kruskal/Prim)"},{letter:"B",text:"Dijkstra (pesos positivos)"},{letter:"C",text:"Mochila 0/1 (vs. mochila fracionária)"},{letter:"D",text:"Problema do caminho mínimo"},{letter:"E",text:"Huffman Coding"}], correctAnswer:"C", explanation:"Mochila 0/1 não é ótima com guloso (exige PD). A fracionária é gulosa-ótima." },

  // ===== PROGRAMAÇÃO ORIENTADA A OBJETOS (10) =====
  { id:"poo_classes_001", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Classes e objetos", difficulty:"fácil", statement:"Sobre classes e objetos em POO, qual afirmação está correta?", alternatives:[{letter:"A",text:"Objeto é a classe instanciada"},{letter:"B",text:"Classe é uma instância de objeto"},{letter:"C",text:"Objeto define a estrutura, classe implementa"},{letter:"D",text:"Classes e objetos são a mesma coisa"},{letter:"E",text:"Objetos não podem ter métodos"}], correctAnswer:"A", explanation:"Classe é o molde/definição. Objeto é uma instância concreta criada a partir da classe." },
  { id:"poo_heranca_002", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Herança e polimorfismo", difficulty:"médio", statement:"Qual é a principal vantagem do polimorfismo em POO?", alternatives:[{letter:"A",text:"Aumentar o acoplamento entre classes"},{letter:"B",text:"Permitir tratar objetos de subclasses por referências da superclasse"},{letter:"C",text:"Eliminar a necessidade de interfaces"},{letter:"D",text:"Reduzir a quantidade de classes no sistema"},{letter:"E",text:"Tornar os atributos públicos"}], correctAnswer:"B", explanation:"Polimorfismo permite que um mesmo método se comporte de formas diferentes conforme o objeto." },
  { id:"poo_encapsulamento_003", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Encapsulamento", difficulty:"fácil", statement:"Qual é o propósito principal do encapsulamento?", alternatives:[{letter:"A",text:"Permitir acesso direto a todos os atributos"},{letter:"B",text:"Proteger dados internos e controlar acesso via métodos"},{letter:"C",text:"Eliminar a necessidade de construtores"},{letter:"D",text:"Tornar todas as classes abstratas"},{letter:"E",text:"Aumentar o acoplamento"}], correctAnswer:"B", explanation:"Encapsulamento esconde detalhes internos e expõe uma interface controlada." },
  { id:"poo_interfaces_004", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Interfaces e classes abstratas", difficulty:"médio", statement:"Diferença entre interface e classe abstrata?", alternatives:[{letter:"A",text:"São exatamente a mesma coisa"},{letter:"B",text:"Interface define contrato sem implementação; classe abstrata pode ter implementação parcial"},{letter:"C",text:"Classe abstrata não pode ter métodos concretos"},{letter:"D",text:"Interface pode ter atributos"},{letter:"E",text:"Java não suporta interfaces"}], correctAnswer:"B", explanation:"Interface = contrato puro (métodos abstratos). Classe abstrata = pode ter estado e métodos concretos." },
  { id:"poo_padroes_005", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Padrões de projeto GoF", difficulty:"médio", statement:"Qual padrão GoF garante que uma classe tenha apenas uma instância?", alternatives:[{letter:"A",text:"Factory Method"},{letter:"B",text:"Observer"},{letter:"C",text:"Singleton"},{letter:"D",text:"Strategy"},{letter:"E",text:"Decorator"}], correctAnswer:"C", explanation:"Singleton restringe a instanciação de uma classe a um único objeto." },
  { id:"poo_solid_006", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Princípios SOLID", difficulty:"médio", statement:"O princípio O (Open/Closed) de SOLID afirma que:", alternatives:[{letter:"A",text:"Classes devem ser abertas para modificação e fechadas para extensão"},{letter:"B",text:"Classes devem ser abertas para extensão e fechadas para modificação"},{letter:"C",text:"Todas as classes devem ser abertas"},{letter:"D",text:"Todas as classes devem ser finais (não herdáveis)"},{letter:"E",text:"Cada classe deve ter apenas um método"}], correctAnswer:"B", explanation:"OCP: estender comportamento sem alterar código existente (via herança, composição, plugins)." },
  { id:"poo_uml_007", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"UML", difficulty:"fácil", statement:"No diagrama de classes UML, o símbolo '+' antes de um atributo significa:", alternatives:[{letter:"A",text:"Privado"},{letter:"B",text:"Protegido"},{letter:"C",text:"Público"},{letter:"D",text:"Estático"},{letter:"E",text:"Final"}], correctAnswer:"C", explanation:"UML: + = público, - = privado, # = protegido, _ = estático." },
  { id:"poo_excecoes_008", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Tratamento de exceções", difficulty:"médio", statement:"Qual bloco é SEMPRE executado no tratamento de exceções, mesmo com erro?", alternatives:[{letter:"A",text:"try"},{letter:"B",text:"catch"},{letter:"C",text:"finally"},{letter:"D",text:"throw"},{letter:"E",text:"throws"}], correctAnswer:"C", explanation:"finally é executado independentemente de ocorrer ou não exceção." },
  { id:"poo_generics_009", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Generics e coleções", difficulty:"médio", statement:"Principal vantagem de generics em Java/C#?", alternatives:[{letter:"A",text:"Reduz a performance"},{letter:"B",text:"Permite reutilização de código com verificação de tipos em tempo de compilação"},{letter:"C",text:"Elimina a necessidade de coleções"},{letter:"D",text:"Permite apenas tipos primitivos"},{letter:"E",text:"Aumenta o acoplamento"}], correctAnswer:"B", explanation:"Generics proporcionam segurança de tipos e reutilização sem casting em runtime." },
  { id:"poo_mvc_010", topic:"Programação Orientada a Objetos", macroarea:"Paradigmas", element:"Padrões arquiteturais", difficulty:"médio", statement:"No padrão MVC, o Controller é responsável por:", alternatives:[{letter:"A",text:"Renderizar a view diretamente"},{letter:"B",text:"Gerenciar os dados do modelo"},{letter:"C",text:"Receber entrada do usuário, processar lógica e coordenar Model e View"},{letter:"D",text:"Armazenar dados no banco"},{letter:"E",text:"Definir o layout CSS"}], correctAnswer:"C", explanation:"Controller recebe requisições, invoca lógica de negócio no Model e seleciona a View." },
];

// Batch 2: BD (10), ES (10), SO (10), RED (10), SD (10)
const batch2: Q[] = [
  // ===== BANCO DE DADOS (10) =====
  { id:"bd_modelo_rel_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"Modelo relacional", difficulty:"fácil", statement:"Relacionamento 1:N entre Departamento e Funcionário. Qual implementação correta?", alternatives:[{letter:"A",text:"Chave estrangeira nos dois lados"},{letter:"B",text:"Chave estrangeira de Departamento em Funcionário"},{letter:"C",text:"Única tabela combinada"},{letter:"D",text:"Sem chave estrangeira"},{letter:"E",text:"Chave primária em ambas"}], correctAnswer:"B", explanation:"No 1:N, a FK do lado '1' vai para o lado 'N'." },
  { id:"bd_algebra_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"Álgebra relacional", difficulty:"difícil", statement:"π_A(R ⨝ R.B=S.B σ_C>10(S)). O que retorna?", alternatives:[{letter:"A",text:"Valores de A de R relacionados com S onde C>10 no join"},{letter:"B",text:"Todos A e C com B igual e C>10"},{letter:"C",text:"Produto cartesiano filtrado"},{letter:"D",text:"Diferença R-S"},{letter:"E",text:"União filtrada"}], correctAnswer:"A", explanation:"Seleciona S com C>10, faz join com R, projeta A." },
  { id:"bd_sql_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"SQL", difficulty:"médio", statement:"Professores que ministram em pelo menos 2 disciplinas. SQL correto?", alternatives:[{letter:"A",text:"SELECT nome WHERE COUNT(disciplina) >= 2"},{letter:"B",text:"SELECT p.nome FROM Professor p JOIN Aula a GROUP BY p.id HAVING COUNT(DISTINCT a.id_disciplina) >= 2"},{letter:"C",text:"SELECT nome FROM Professor WHERE id IN (SELECT id FROM Aula GROUP BY disciplina)"},{letter:"D",text:"SELECT nome WHERE COUNT >= 2"},{letter:"E",text:"SELECT DISTINCT nome WHERE disciplina > 1"}], correctAnswer:"B", explanation:"GROUP BY professor + HAVING COUNT(DISTINCT disciplina) >= 2." },
  { id:"bd_norm_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"Normalização", difficulty:"médio", statement:"Tabela Venda com PK=(num_venda, cod_produto). Dependências parciais existem?", alternatives:[{letter:"A",text:"Está na 2NF"},{letter:"B",text:"Viola 2NF: nome_cliente depende de cpf_cliente, descricao de cod_produto"},{letter:"C",text:"Viola apenas 3NF"},{letter:"D",text:"Está na 1NF apenas por grupo repetitivo"},{letter:"E",text:"Está na BCNF"}], correctAnswer:"B", explanation:"Dependências parciais de atributos não-chave em partes da PK composta violam 2NF." },
  { id:"bd_chaves_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"Chaves", difficulty:"fácil", statement:"Tabela Aluno(matricula, cpf, nome). Ambos matricula e cpf são únicos. Sobre chaves?", alternatives:[{letter:"A",text:"Ambas são PK"},{letter:"B",text:"São chaves candidatas; apenas uma é escolhida como PK"},{letter:"C",text:"PK deve ser composta"},{letter:"D",text:"CPF não pode ser candidata"},{letter:"E",text:"PK é obrigatoriamente nome"}], correctAnswer:"B", explanation:"Duas chaves candidatas, mas apenas uma pode ser PK. Matricula geralmente é preferida." },
  { id:"bd_transacoes_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"Transações ACID", difficulty:"médio", statement:"Transferência bancária: T1 debita A, credita B. T2 consulta saldo total. Em qual nível T2 pode ver saldo inconsistente?", alternatives:[{letter:"A",text:"Serializable"},{letter:"B",text:"Read Committed"},{letter:"C",text:"Read Uncommitted (dirty read)"},{letter:"D",text:"Repeatable Read"},{letter:"E",text:"Nenhum nível permite isso"}], correctAnswer:"C", explanation:"Read Uncommitted permite dirty reads, T2 pode ver débito sem crédito." },
  { id:"bd_indices_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"Índices", difficulty:"médio", statement:"Tabela Pedidos com 5M registros. Buscas frequentes por numero_pedido, data_pedido e cpf+status. Melhor estratégia?", alternatives:[{letter:"A",text:"Índice composto único"},{letter:"B",text:"B-tree em numero_pedido, B-tree em data_pedido, composto (cpf, status)"},{letter:"C",text:"Hash em todas colunas"},{letter:"D",text:"Sem índices (volume pequeno)"},{letter:"E",text:"Apenas em cpf"}], correctAnswer:"B", explanation:"Índices especializados por padrão de consulta são mais eficientes." },
  { id:"bd_join_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"JOINs", difficulty:"médio", statement:"Diferença entre INNER JOIN e LEFT JOIN?", alternatives:[{letter:"A",text:"São idênticos"},{letter:"B",text:"LEFT retorna todos da tabela esquerda mesmo sem correspondência"},{letter:"C",text:"INNER retorna mais resultados"},{letter:"D",text:"LEFT é mais lento sempre"},{letter:"E",text:"Não há diferença prática"}], correctAnswer:"B", explanation:"LEFT JOIN preserva todos registros da tabela esquerda, preenchendo NULLs onde não há match." },
  { id:"bd_views_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"Views e subconsultas", difficulty:"médio", statement:"Vantagem principal de Views?", alternatives:[{letter:"A",text:"Aumentar velocidade de consulta"},{letter:"B",text:"Simplificar consultas complexas e restringir acesso a dados"},{letter:"C",text:"Armazenar dados fisicamente"},{letter:"D",text:"Substituir índices"},{letter:"E",text:"Eliminar necessidade de JOINs"}], correctAnswer:"B", explanation:"Views abstraem complexidade e podem ser usadas para segurança (colunas filtradas)." },
  { id:"bd_nosql_001", topic:"Banco de Dados", macroarea:"Desenvolvimento", element:"NoSQL", difficulty:"médio", statement:"Startup com perfis de campos variáveis, alta disponibilidade e escalabilidade horizontal. Qual NoSQL?", alternatives:[{letter:"A",text:"Grafos (Neo4j)"},{letter:"B",text:"Colunas (Cassandra)"},{letter:"C",text:"Documentos (MongoDB) - schema flexível, sharding, replica sets"},{letter:"D",text:"Chave-valor (Redis)"},{letter:"E",text:"Relacional com tabelas dinâmicas"}], correctAnswer:"C", explanation:"MongoDB permite documentos com estrutura variável, escalabilidade horizontal e alta disponibilidade." },

  // ===== ENGENHARIA DE SOFTWARE (10) =====
  { id:"es_modelos_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Modelos de processo", difficulty:"médio", statement:"Sistema crítico de aviação com requisitos estáveis. Modelo mais adequado?", alternatives:[{letter:"A",text:"Scrum (ágil)"},{letter:"B",text:"Cascata (Waterfall) - planejamento rigoroso, documentação completa"},{letter:"C",text:"Prototipação"},{letter:"D",text:"Espiral"},{letter:"E",text:"Incremental"}], correctAnswer:"B", explanation:"Sistemas safety-critical com requisitos estáveis se beneficiam de Cascata com validação formal." },
  { id:"es_agil_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Métodos ágeis", difficulty:"fácil", statement:"No Scrum, o artefato com itens selecionados para a Sprint é:", alternatives:[{letter:"A",text:"Product Backlog"},{letter:"B",text:"Sprint Backlog"},{letter:"C",text:"Release Backlog"},{letter:"D",text:"Burndown Chart"},{letter:"E",text:"Impediment Log"}], correctAnswer:"B", explanation:"Sprint Backlog contém os itens selecionados para a Sprint e o plano de entrega." },
  { id:"es_requisitos_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Requisitos", difficulty:"médio", statement:"R1: adicionar ao carrinho, R2: carregar em <3s, R3: calcular frete, R4: suportar 10k usuários. Funcionais e não funcionais?", alternatives:[{letter:"A",text:"Todos funcionais"},{letter:"B",text:"R1,R3 funcionais; R2,R4 não funcionais"},{letter:"C",text:"R1,R2,R4 funcionais; R3 não funcional"},{letter:"D",text:"R2,R3 funcionais; R1,R4 não"},{letter:"E",text:"R1 funcional; R2,R3,R4 não funcionais"}], correctAnswer:"B", explanation:"R1,R3 descrevem comportamento (funcional). R2 (performance) e R4 (escala) são não funcionais." },
  { id:"es_testes_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Testes de software", difficulty:"difícil", statement:"Função com if-else(2 caminhos), switch(4 casos), while, for aninhado. Complexidade ciclomática?", alternatives:[{letter:"A",text:"5"},{letter:"B",text:"7"},{letter:"C",text:"9"},{letter:"D",text:"11"},{letter:"E",text:"3"}], correctAnswer:"B", explanation:"V(G) = 1 + decisões = 1 + (1+3+1+1) = 7." },
  { id:"es_metricas_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Métricas", difficulty:"médio", statement:"Atualizar tabela INSS para nova legislação. Tipo de manutenção?", alternatives:[{letter:"A",text:"Corretiva"},{letter:"B",text:"Adaptativa (mudança no ambiente externo)"},{letter:"C",text:"Perfectiva"},{letter:"D",text:"Preventiva"},{letter:"E",text:"Refatoração"}], correctAnswer:"B", explanation:"Mudança legislativa = alteração no ambiente externo = manutenção adaptativa." },
  { id:"es_qualidade_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Qualidade ISO/IEC 25010", difficulty:"médio", statement:"99,9% uptime, fácil aprender, proteger dados, integrar com outros sistemas. Quais características ISO/IEC 25010?", alternatives:[{letter:"A",text:"Eficiência, Usabilidade, Segurança, Interoperabilidade"},{letter:"B",text:"Confiabilidade, Usabilidade, Confidencialidade, Compatibilidade"},{letter:"C",text:"Disponibilidade, Acessibilidade, Integridade, Portabilidade"},{letter:"D",text:"Maturidade, Apreensibilidade, Autenticidade, Modularidade"},{letter:"E",text:"Tolerância a falhas, Operabilidade, Não-repúdio, Adaptabilidade"}], correctAnswer:"B", explanation:"99,9%→Confiabilidade, fácil aprender→Usabilidade, proteger→Segurança, integrar→Compatibilidade." },
  { id:"es_devops_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"DevOps/CI-CD", difficulty:"médio", statement:"Commit→build→testes→deploy automático para produção. Qual afirmação está correta?", alternatives:[{letter:"A",text:"Continuous Delivery apenas"},{letter:"B",text:"Continuous Deployment - deploy automático sem intervenção humana"},{letter:"C",text:"Não é CI/CD (falta validação manual)"},{letter:"D",text:"CI só executa testes unitários"},{letter:"E",text:"Requer 3 commits simultâneos"}], correctAnswer:"B", explanation:"CD (Deployment) = deploy automático após testes passarem, sem aprovação humana." },
  { id:"es_git_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Versionamento Git", difficulty:"médio", statement:"Push rejeitado (Alice e Bob editaram mesmo arquivo). Qual solução segura?", alternatives:[{letter:"A",text:"git push --force"},{letter:"B",text:"git pull --rebase, resolver conflitos, git push"},{letter:"C",text:"git reset --hard origin/main"},{letter:"D",text:"git merge sem resolver conflitos"},{letter:"E",text:"Criar branch nova"}], correctAnswer:"B", explanation:"pull --rebase aplica commits locais sobre histórico atualizado, mantendo linearidade." },
  { id:"es_casouso_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Casos de uso UML", difficulty:"médio", statement:"Relação entre 'Emprestar Livro' e 'Notificar Disponibilidade' (opcional)?", alternatives:[{letter:"A",text:"«include» - obrigatório"},{letter:"B",text:"«extend» - opcional sob condição específica"},{letter:"C",text:"«generalization»"},{letter:"D",text:"Sem relação"},{letter:"E",text:"«extend» na direção errada"}], correctAnswer:"B", explanation:"«extend» é para comportamento opcional/condicional. «include» é obrigatório." },
  { id:"es_documento_001", topic:"Engenharia de Software", macroarea:"Desenvolvimento", element:"Documentação", difficulty:"fácil", statement:"Qual tipo de documentação descreve COMO o sistema é implementado?", alternatives:[{letter:"A",text:"Documentação de usuário"},{letter:"B",text:"Documentação técnica/arquitetural"},{letter:"C",text:"Manual de instalação"},{letter:"D",text:"Release notes"},{letter:"E",text:"FAQ"}], correctAnswer:"B", explanation:"Documentação técnica descreve arquitetura, APIs, código e decisões de design." },

  // ===== SISTEMAS OPERACIONAIS (10) =====
  { id:"so_processos_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Processos e threads", difficulty:"médio", statement:"Sobre modelo de threads 1:1 (kernel-level), é correto:", alternatives:[{letter:"A",text:"Cada thread usuário = thread kernel, paralelismo real em SMP, mas criação mais custosa"},{letter:"B",text:"Threads gerenciadas pelo SO, melhor paralelismo e menor custo"},{letter:"C",text:"Todas gerenciadas exclusivamente pelo kernel sem biblioteca"},{letter:"D",text:"Sempre inferior ao N:1"},{letter:"E",text:"N:1 permite paralelismo em multiprocessadores"}], correctAnswer:"A", explanation:"1:1 mapeia cada thread user para kernel thread, permitindo paralelismo real mas com maior custo." },
  { id:"so_escalonamento_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Escalonamento", difficulty:"médio", statement:"Round Robin (quantum=4): P1(8), P2(4), P3(9), P4(5), todos chegam em t=0. Tempo médio de turnaround?", alternatives:[{letter:"A",text:"18,0"},{letter:"B",text:"18,75"},{letter:"C",text:"22,0"},{letter:"D",text:"26,5"},{letter:"E",text:"15,25"}], correctAnswer:"B", explanation:"Turnaround: P1=19, P2=7, P3=25, P4=24. Média=(19+7+25+24)/4=18,75." },
  { id:"so_deadlock_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Deadlock", difficulty:"fácil", statement:"P1 segura R1 pede R2, P2 segura R2 pede R3, P3 segura R3 pede R1. Há deadlock?", alternatives:[{letter:"A",text:"Não, cada processo segura um recurso"},{letter:"B",text:"Sim, 4 condições de Coffman satisfeitas"},{letter:"C",text:"Sim, mas apenas 3 condições"},{letter:"D",text:"Não, preempção resolve"},{letter:"E",text:"Starvation apenas"}], correctAnswer:"B", explanation:"Exclusão mútua, posse e espera, não preemptibilidade e espera circular = deadlock." },
  { id:"so_memoria_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Gerência de memória", difficulty:"médio", statement:"Memória física 256MB, páginas 4KB, endereçamento lógico 64MB. Quantas entradas na tabela de páginas?", alternatives:[{letter:"A",text:"65.536"},{letter:"B",text:"16.384"},{letter:"C",text:"32.768"},{letter:"D",text:"8.192"},{letter:"E",text:"131.072"}], correctAnswer:"B", explanation:"64MB/4KB = 64×1024/4 = 16.384 entradas." },
  { id:"so_virtual_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Memória virtual", difficulty:"médio", statement:"Algoritmo de substituição de páginas LRU. Qual afirmação está correta?", alternatives:[{letter:"A",text:"Substitui página mais recentemente usada"},{letter:"B",text:"Substitui página há mais tempo sem acesso"},{letter:"C",text:"Substitui página aleatoriamente"},{letter:"D",text:"Substitui a primeira que entrou (FIFO)"},{letter:"E",text:"Substitui a página mais acessada"}], correctAnswer:"B", explanation:"LRU (Least Recently Used) substitui a página não acessada há mais tempo." },
  { id:"so_arquivos_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Sistemas de arquivos", difficulty:"fácil", statement:"Qual método de alocação sofre de fragmentação externa mas não interna?", alternatives:[{letter:"A",text:"Alocação contígua"},{letter:"B",text:"Alocação encadeada"},{letter:"C",text:"Alocação indexada"},{letter:"D",text:"Alocação por hashing"},{letter:"E",text:"Nenhuma"}], correctAnswer:"A", explanation:"Alocação contígua sofre fragmentação externa (espaço insuficiente contíguo)." },
  { id:"so_io_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Gerenciamento de I/O", difficulty:"médio", statement:"Qual técnica de I/O permite que a CPU execute outras tarefas enquanto espera operação de I/O?", alternatives:[{letter:"A",text:"I/O programado (polling)"},{letter:"B",text:"Interrupções"},{letter:"C",text:"I/O síncrono bloqueante"},{letter:"D",text:"Acesso direto à memória (DMA)"},{letter:"E",text:"B e D estão corretas"}], correctAnswer:"E", explanation:"Interrupções e DMA permitem que a CPU não fique ociosa esperando I/O." },
  { id:"so_sync_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Sincronização", difficulty:"difícil", statement:"Sobre semáforos, qual afirmação está correta?", alternatives:[{letter:"A",text:"Semáforo binário é o mesmo que mutex"},{letter:"B",text:"Semáforo com valor inicial 0 bloqueia threads até que alguém faça signal"},{letter:"C",text:"Wait decrementa o valor"},{letter:"D",text:"B e C estão corretas"},{letter:"E",text:"Semáforos não resolvem exclusão mútua"}], correctAnswer:"D", explanation:"Semáforo=0 bloqueia no wait. Wait(S): se S>0, S--; senão bloqueia. Signal(S): S++." },
  { id:"so_seguranca_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"Segurança de SO", difficulty:"médio", statement:"Princípio do menor privilégio no contexto de SO significa:", alternatives:[{letter:"A",text:"Todos os processos têm acesso root"},{letter:"B",text:"Cada processo recebe apenas os privilégios mínimos necessários"},{letter:"C",text:"Não há controle de acesso"},{letter:"D",text:"Todos os usuários são administradores"},{letter:"E",text:"Senhas não são necessárias"}], correctAnswer:"B", explanation:"Menor privilégio = executar com permissões mínimas para reduzir superfície de ataque." },
  { id:"so_linux_001", topic:"Sistemas Operacionais", macroarea:"Desenvolvimento", element:"SO comerciais", difficulty:"fácil", statement:"Qual comando no Linux lista os processos em execução?", alternatives:[{letter:"A",text:"ls"},{letter:"B",text:"ps"},{letter:"C",text:"cd"},{letter:"D",text:"mkdir"},{letter:"E",text:"cp"}], correctAnswer:"B", explanation:"ps (process status) lista processos. ls lista arquivos." },

  // ===== REDES (10) =====
  { id:"red_osi_001", topic:"Redes", macroarea:"Desenvolvimento", element:"Modelo OSI/TCP-IP", difficulty:"fácil", statement:"Quantas camadas tem o modelo OSI?", alternatives:[{letter:"A",text:"4"},{letter:"B",text:"5"},{letter:"C",text:"6"},{letter:"D",text:"7"},{letter:"E",text:"8"}], correctAnswer:"D", explanation:"OSI tem 7 camadas: Física, Enlace, Rede, Transporte, Sessão, Apresentação, Aplicação." },
  { id:"red_tcp_udp_001", topic:"Redes", macroarea:"Desenvolvimento", element:"TCP/UDP", difficulty:"médio", statement:"Diferença fundamental entre TCP e UDP?", alternatives:[{letter:"A",text:"Usam portas diferentes apenas"},{letter:"B",text:"TCP é orientado a conexão e confiável; UDP não é orientado a conexão e não garante entrega"},{letter:"C",text:"UDP é mais lento"},{letter:"D",text:"TCP não usa checksum"},{letter:"E",text:"São idênticos"}], correctAnswer:"B", explanation:"TCP: handshake, garantia de entrega, ordenação. UDP: sem conexão, best-effort, menor overhead." },
  { id:"red_http_001", topic:"Redes", macroarea:"Desenvolvimento", element:"Protocolos aplicação", difficulty:"médio", statement:"Qual código HTTP indica 'recurso não encontrado'?", alternatives:[{letter:"A",text:"200"},{letter:"B",text:"301"},{letter:"C",text:"403"},{letter:"D",text:"404"},{letter:"E",text:"500"}], correctAnswer:"D", explanation:"404 = Not Found. 200=OK, 301=Redirect, 403=Forbidden, 500=Server Error." },
  { id:"red_ip_001", topic:"Redes", macroarea:"Desenvolvimento", element:"Endereçamento IP", difficulty:"fácil", statement:"Qual classe de IP permite mais hosts por rede?", alternatives:[{letter:"A",text:"Classe A"},{letter:"B",text:"Classe B"},{letter:"C",text:"Classe C"},{letter:"D",text:"Classe D"},{letter:"E",text:"Classe E"}], correctAnswer:"A", explanation:"Classe A: rede com 8 bits (16M+ hosts). Classe B: 16 bits (65K). Classe C: 24 bits (254)." },
  { id:"red_subnet_001", topic:"Redes", macroarea:"Desenvolvimento", element:"Sub-redes", difficulty:"médio", statement:"Rede 192.168.1.0/24 subdividida em /26. Quantas sub-redes?", alternatives:[{letter:"A",text:"2"},{letter:"B",text:"4"},{letter:"C",text:"8"},{letter:"D",text:"16"},{letter:"E",text:"32"}], correctAnswer:"B", explanation:"/26 empresta 2 bits → 2²=4 sub-redes de 64 hosts cada." },
  { id:"red_rota_001", topic:"Redes", macroarea:"Desenvolvimento", element:"Roteamento", difficulty:"médio", statement:"Protocolo de roteamento que usa algoritmo de menor caminho (Dijkstra)?", alternatives:[{letter:"A",text:"RIP"},{letter:"B",text:"OSPF"},{letter:"C",text:"BGP"},{letter:"D",text:"ARP"},{letter:"E",text:"ICMP"}], correctAnswer:"B", explanation:"OSPF usa Dijkstra. RIP usa Bellman-Ford. BGP é path vector." },
  { id:"red_vlan_001", topic:"Redes", macroarea:"Desenvolvimento", element:"VLANs", difficulty:"médio", statement:"Benefício principal de VLANs?", alternatives:[{letter:"A",text:"Aumentar a largura de banda"},{letter:"B",text:"Segmentação lógica para segurança e gestão de broadcast"},{letter:"C",text:"Substituir roteadores"},{letter:"D",text:"Eliminar necessidade de switch"},{letter:"E",text:"Aumentar a velocidade do link físico"}], correctAnswer:"B", explanation:"VLANs segmentam broadcast domains logicamente, melhorando segurança e performance." },
  { id:"red_firewall_001", topic:"Redes", macroarea:"Desenvolvimento", element:"Firewall", difficulty:"médio", statement:"Sobre firewalls e NAT, qual afirmação está correta?", alternatives:[{letter:"A",text:"NAT não altera endereços IP"},{letter:"B",text:"NAT traduz endereços privados para públicos, permitindo saída para internet"},{letter:"C",text:"Firewall não filtra tráfego"},{letter:"D",text:"NAT é o mesmo que firewall"},{letter:"E",text:"VPN usa protocolo FTP"}], correctAnswer:"B", explanation:"NAT (Network Address Translation) mapeia IPs privados para IPs públicos na saída." },
  { id:"red_wifi_001", topic:"Redes", macroarea:"Desenvolvimento", element:"Redes sem fio", difficulty:"fácil", statement:"Qual protocolo de segurança Wi-Fi é considerado mais seguro?", alternatives:[{letter:"A",text:"WEP"},{letter:"B",text:"WPA"},{letter:"C",text:"WPA2/WPA3"},{letter:"D",text:"Open (sem segurança)"},{letter:"E",text:"WPS"}], correctAnswer:"C", explanation:"WPA2 (AES) e WPA3 são os padrões atuais. WEP está quebrado há décadas." },
  { id:"red_dns_001", topic:"Redes", macroarea:"Desenvolvimento", element:"DNS", difficulty:"médio", statement:"Qual é a função principal do DNS?", alternatives:[{letter:"A",text:"Criptografar dados"},{letter:"B",text:"Converter nomes de domínio em endereços IP"},{letter:"C",text:"Atribuir endereços IP automaticamente"},{letter:"D",text:"Filtrar conteúdo web"},{letter:"E",text:"Rotear pacotes entre redes"}], correctAnswer:"B", explanation:"DNS (Domain Name System) resolve nomes como www.google.com para endereços IP." },

  // ===== SISTEMAS DISTRIBUÍDOS (10) =====
  { id:"sd_arquitetura_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Arquiteturas", difficulty:"médio", statement:"Vantagem da arquitetura de microserviços sobre monolítica?", alternatives:[{letter:"A",text:"Simplificação do deploy"},{letter:"B",text:"Escalabilidade independente, desacoplamento e resiliência"},{letter:"C",text:"Menor latência"},{letter:"D",text:"Sem necessidade de rede"},{letter:"E",text:"Mais fácil de debugar"}], correctAnswer:"B", explanation:"Microserviços permitem escalar, desenvolver e fazer deploy de serviços independentemente." },
  { id:"sd_comunicacao_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Comunicação", difficulty:"médio", statement:"Diferença entre RPC e mensageria assíncrona?", alternatives:[{letter:"A",text:"São idênticos"},{letter:"B",text:"RPC é síncrono (bloqueante); mensageria é assíncrona (desacoplada)"},{letter:"C",text:"RPC é mais lento"},{letter:"D",text:"Mensageria é sempre síncrona"},{letter:"E",text:"RPC não usa rede"}], correctAnswer:"B", explanation:"RPC: chamada remota bloqueante. Mensageria: produtor envia, consumidor processa depois." },
  { id:"sd_cap_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Teorema CAP", difficulty:"difícil", statement:"Teorema CAP: em presença de partição de rede, deve-se escolher entre:", alternatives:[{letter:"A",text:"Consistência e Disponibilidade simultaneamente"},{letter:"B",text:"Consistência (CP) ou Disponibilidade (AP)"},{letter:"C",text:"Partição e Disponibilidade"},{letter:"D",text:"Consistência e Partição"},{letter:"E",text:"Não é possível escolher"}], correctAnswer:"B", explanation:"CAP: C+A+P simultâneos impossível. Na partição: escolher consistência (CP) ou disponibilidade (AP)." },
  { id:"sd_replicacao_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Replicação", difficulty:"médio", statement:"Qual modelo de consistência permite leituras eventualmente atualizadas?", alternatives:[{letter:"A",text:"Fortemente consistente"},{letter:"B",text:"Consistência eventual"},{letter:"C",text:"Consistência sequencial"},{letter:"D",text:"Consistência causal"},{letter:"E",text:"Linearizável"}], correctAnswer:"B", explanation:"Consistência eventual: réplicas convergem sem garantia de tempo, mas eventualmente ficam iguais." },
  { id:"sd_2pc_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Transações distribuídas", difficulty:"difícil", statement:"No protocolo 2PC, qual fase acontece primeiro?", alternatives:[{letter:"A",text:"Commit phase"},{letter:"B",text:"Prepare/voting phase"},{letter:"C",text:"Abort phase"},{letter:"D",text:"Recovery phase"},{letter:"E",text:"Timeout phase"}], correctAnswer:"B", explanation:"2PC: 1) Fase de preparo (votação) → 2) Fase de commit (execução)." },
  { id:"sd_balanceamento_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Balanceamento de carga", difficulty:"médio", statement:"Qual algoritmo de load balancing distribui equitativamente requisições?", alternatives:[{letter:"A",text:"Random"},{letter:"B",text:"Round Robin"},{letter:"C",text:"IP Hash"},{letter:"D",text:"Least Connections"},{letter:"E",text:"Weighted"}], correctAnswer:"B", explanation:"Round Robin distribui requisições sequencialmente entre servidores de forma equitativa." },
  { id:"sd_nuvem_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Computação em nuvem", difficulty:"fácil", statement:"IaaS, PaaS, SaaS. Qual fornece apenas infraestrutura (VMs, rede, storage)?", alternatives:[{letter:"A",text:"SaaS"},{letter:"B",text:"PaaS"},{letter:"C",text:"IaaS - infraestrutura como serviço"},{letter:"D",text:"Todos fornecem VMs"},{letter:"E",text:"Nenhum"}], correctAnswer:"C", explanation:"IaaS fornece infraestrutura. PaaS adiciona runtime/banco. SaaS é software pronto para uso." },
  { id:"sd_docker_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Containers", difficulty:"médio", statement:"Vantagem de containers sobre VMs?", alternatives:[{letter:"A",text:"Maior isolamento"},{letter:"B",text:"Menor overhead, inicialização mais rápida, portabilidade"},{letter:"C",text:"Containers usam mais recursos"},{letter:"D",text:"VMs são mais leves"},{letter:"E",text:"Não há diferença"}], correctAnswer:"B", explanation:"Containers compartilham o kernel do host, sendo mais leves e rápidos que VMs." },
  { id:"sd_api_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"API Gateway", difficulty:"médio", statement:"Função do API Gateway em arquitetura de microserviços?", alternatives:[{letter:"A",text:"Armazenar dados"},{letter:"B",text:"Ponto único de entrada, roteamento, autenticação e rate limiting"},{letter:"C",text:"Substituir banco de dados"},{letter:"D",text:"Apenas autenticação"},{letter:"E",text:"Compilar código"}], correctAnswer:"B", explanation:"API Gateway centraliza roteamento, autenticação, rate limiting e composição de chamadas." },
  { id:"sd_mensageria_001", topic:"Sistemas Distribuídos", macroarea:"Desenvolvimento", element:"Mensageria", difficulty:"médio", statement:"Diferença entre filas e tópicos em mensageria?", alternatives:[{letter:"A",text:"São idênticos"},{letter:"B",text:"Filas: um consumidor por mensagem. Tópicos: todos inscritos recebem (pub/sub)"},{letter:"C",text:"Tópicos são mais lentos"},{letter:"D",text:"Filas usam multicast"},{letter:"E",text:"Tópicos usam unicast"}], correctAnswer:"B", explanation:"Filas = point-to-point. Tópicos = publish/subscribe (broadcast)." },
];

// Batch 3: CRI (10), IA (10), CD (10), ETI (5), LEG (5)
const batch3: Q[] = [
  // ===== CRIPTOGRAFIA (10) =====
  { id:"cripto_sim_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Criptografia simétrica", difficulty:"fácil", statement:"Qual algoritmo simétrico é recomendado pela NIST para alto sigilo?", alternatives:[{letter:"A",text:"3DES"},{letter:"B",text:"AES-256"},{letter:"C",text:"Blowfish"},{letter:"D",text:"RC4"},{letter:"E",text:"DES"}], correctAnswer:"B", explanation:"AES-256 com chaves de 256 bits é aprovado para proteção de alto sigilo pela NIST." },
  { id:"cripto_cbc_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Modos de operação", difficulty:"médio", statement:"No modo CBC do AES, como cada bloco é cifrado?", alternatives:[{letter:"A",text:"Independentemente (ECB)"},{letter:"B",text:"C_i = E_K(P_i XOR C_{i-1}), com IV para o primeiro bloco"},{letter:"C",text:"Sem IV necessário"},{letter:"D",text:"IV reutilizado sempre"},{letter:"E",text:"CBC vulnerável apenas com AES-128"}], correctAnswer:"B", explanation:"CBC encadeia blocos: cada bloco cifrado depende do anterior, com IV para o primeiro." },
  { id:"cripto_assim_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Criptografia assimétrica", difficulty:"médio", statement:"Cliente cifra com chave pública do servidor (confidencialidade) e servidor assina com chave privada (autenticidade). Qual alternativa descreve isso?", alternatives:[{letter:"A",text:"Cliente cifra com chave privada"},{letter:"B",text:"Cifrar com chave pública do destinatário + assinar com chave privada do remetente"},{letter:"C",text:"Cifrar com chave privada do destinatário"},{letter:"D",text:"Apenas chaves públicas"},{letter:"E",text:"Apenas chaves privadas"}], correctAnswer:"B", explanation:"RSA: cifra com chave pública do destinatário (confidencialidade) + assina com chave privada (autenticidade)." },
  { id:"cripto_hash_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Funções hash", difficulty:"fácil", statement:"Para armazenamento seguro de senhas, qual é a prática recomendada?", alternatives:[{letter:"A",text:"MD5 sem salt"},{letter:"B",text:"SHA-1 com salt"},{letter:"C",text:"bcrypt ou Argon2 com salt"},{letter:"D",text:"Texto claro"},{letter:"E",text:"SHA-256 sem salt"}], correctAnswer:"C", explanation:"bcrypt/Argon2 são lentas (anti-força bruta) e usam salt por usuário." },
  { id:"cripto_assinatura_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Assinatura digital", difficulty:"médio", statement:"Passos corretos da assinatura digital?", alternatives:[{letter:"A",text:"Cifrar documento inteiro com chave privada"},{letter:"B",text:"Calcular hash do documento, cifrar o hash com chave privada"},{letter:"C",text:"Cifrar documento com chave pública"},{letter:"D",text:"Hash + cifrar com chave pública"},{letter:"E",text:"Enviar em texto claro"}], correctAnswer:"B", explanation:"Assinatura digital = hash cifrado com chave privada. Eficiente para documentos grandes." },
  { id:"cripto_ssl_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"SSL/TLS", difficulty:"médio", statement:"Melhoria principal do TLS 1.3 sobre 1.2?", alternatives:[{letter:"A",text:"Handshake em 4 vias"},{letter:"B",text:"Handshake em 1-RTT, remoção de algoritmos inseguros"},{letter:"C",text:"Suporte a RC4"},{letter:"D",text:"Compatível com SSL 3.0"},{letter:"E",text:"Certificado opcional"}], correctAnswer:"B", explanation:"TLS 1.3: handshake 1-RTT (ou 0-RTT), remove RC4/DES/3DES/CBC estático." },
  { id:"cripto_rsa_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"RSA/Computação quântica", difficulty:"difícil", statement:"Sobre o algoritmo de Shor e RSA?", alternatives:[{letter:"A",text:"Shor fatora em tempo polinomial, ameaçando RSA"},{letter:"B",text:"Shor afeta apenas criptografia simétrica"},{letter:"C",text:"RSA-4096 é imune ao Shor"},{letter:"D",text:"Shor opera em tempo exponencial"},{letter:"E",text:"RSA-4096 resolve a ameaça quântica"}], correctAnswer:"A", explanation:"Shor fatora inteiros em O((log n)³), quebrando RSA quando computadores quânticos forem viáveis." },
  { id:"cripto_chaves_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Gestão de chaves", difficulty:"médio", statement:"500 funcionários, uma chave simétrica por par. Total de chaves?", alternatives:[{letter:"A",text:"500"},{letter:"B",text:"1.000"},{letter:"C",text:"124.750 (n(n-1)/2)"},{letter:"D",text:"250.000"},{letter:"E",text:"249.500"}], correctAnswer:"C", explanation:"C(500,2) = 500×499/2 = 124.750 chaves. É por isso que criptografia assimétrica é preferida." },
  { id:"cripto_pki_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Certificados e PKI", difficulty:"médio", statement:"Função de uma Certificate Authority (CA)?", alternatives:[{letter:"A",text:"Armazenar senhas"},{letter:"B",text:"Emitir e gerenciar certificados digitais, atestando a identidade"},{letter:"C",text:"Criptografar dados"},{letter:"D",text:"Filtrar tráfego de rede"},{letter:"E",text:"Gerenciar DNS"}], correctAnswer:"B", explanation:"CA emite certificados que vinculam chaves públicas a identidades verificadas." },
  { id:"cripto_estego_001", topic:"Criptografia", macroarea:"Segurança/IA", element:"Esteganografia", difficulty:"médio", statement:"Diferença entre esteganografia e criptografia?", alternatives:[{letter:"A",text:"São sinônimos"},{letter:"B",text:"Criptografia oculta o significado; esteganografia oculta a existência da mensagem"},{letter:"C",text:"Esteganografia não precisa de chave"},{letter:"D",text:"Criptografia altera tamanho perceptível"},{letter:"E",text:"Esteganografia só funciona com texto"}], correctAnswer:"B", explanation:"Criptografia = esconder significado. Esteganografia = esconder existência (LSB em imagens, etc.)." },

  // ===== INTELIGÊNCIA ARTIFICIAL (10) =====
  { id:"ia_busca_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Busca", difficulty:"médio", statement:"Sobre o algoritmo A* com heurística admissível:", alternatives:[{letter:"A",text:"Sempre ótimo mesmo com heurística que superestima"},{letter:"B",text:"Completo e ótimo com heurística admissível (nunca superestima)"},{letter:"C",text:"Igual ao BFS com h=0, perdendo optimalidade"},{letter:"D",text:"Sempre expande menos nós que Dijkstra"},{letter:"E",text:"Não funciona com pesos"}], correctAnswer:"B", explanation:"A* com heurística admissível é completo e ótimo em grafos com custos positivos." },
  { id:"ia_ml_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Aprendizado de máquina", difficulty:"fácil", statement:"Classificar emails como spam/não spam com 10.000 emails rotulados. Tipo de aprendizado?", alternatives:[{letter:"A",text:"Não supervisionado"},{letter:"B",text:"Por reforço"},{letter:"C",text:"Supervisionado (dados rotulados)"},{letter:"D",text:"Semi-supervisionado"},{letter:"E",text:"Por transferência"}], correctAnswer:"C", explanation:"Dados com rótulos (labels) = aprendizado supervisionado." },
  { id:"ia_rn_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Redes neurais", difficulty:"médio", statement:"Rede com entrada 784, ocultas 128/64 (ReLU), saída 10 (softmax). O que softmax produz?", alternatives:[{letter:"A",text:"Valores negativos"},{letter:"B",text:"Distribuição de probabilidade sobre as 10 classes"},{letter:"C",text:"Binary output"},{letter:"D",text:"Valores >1"},{letter:"E",text:"Integers only"}], correctAnswer:"B", explanation:"Softmax converte saídas em probabilidades (0 a 1, soma = 1). Classe prevista = argmax." },
  { id:"ia_overfitting_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Overfitting/Underfitting", difficulty:"médio", statement:"Modelo A: treino MSE=5K, teste MSE=48K. Modelo C: treino=32K, teste=33K. Análise?", alternatives:[{letter:"A",text:"A é melhor (menor erro treino)"},{letter:"B",text:"B sofre underfitting"},{letter:"C",text:"A: overfitting. C: bom balanceamento (erros similares e menores)"},{letter:"D",text:"Todos perfeitamente ajustados"},{letter:"E",text:"C sofre overfitting"}], correctAnswer:"C", explanation:"Gap grande treino-teste = overfitting. Erros similares e baixos = bom ajuste." },
  { id:"ia_regressao_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Regressão e classificação", difficulty:"fácil", statement:"Prever expectativa de vida (contínua) e diagnosticar diabetes (categórica). Tipos?", alternatives:[{letter:"A",text:"Ambos regressão"},{letter:"B",text:"Ambos classificação"},{letter:"C",text:"I: regressão. II: classificação"},{letter:"D",text:"I: classificação multiclasse. II: regressão"},{letter:"E",text:"Nenhum é supervisionado"}], correctAnswer:"C", explanation:"Variável alvo contínua = regressão. Variável categórica = classificação." },
  { id:"ia_nlp_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"NLP", difficulty:"difícil", statement:"Sobre word embeddings (Word2Vec, GloVe):", alternatives:[{letter:"A",text:"Word2Vec usa matriz de coocorrência global"},{letter:"B",text:"Capturam relações semânticas, permitindo operações como rei-homem+mulher≈rainha"},{letter:"C",text:"Só representam palavras individuais"},{letter:"D",text:"Bag-of-words é superior"},{letter:"E",text:"TF-IDF produz embeddings densos neurais"}], correctAnswer:"B", explanation:"Embeddings capturam semântica vetorial: rei-homem+mulher ≈ rainha." },
  { id:"ia_cnn_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Visão computacional", difficulty:"médio", statement:"YOLO vs R-CNN para detecção de objetos:", alternatives:[{letter:"A",text:"YOLO mais lento"},{letter:"B",text:"YOLO: grade + previsão simultânea em uma passagem, significativamente mais rápido"},{letter:"C",text:"R-CNN sempre melhor"},{letter:"D",text:"São idênticos em velocidade"},{letter:"E",text:"YOLO não faz detecção em tempo real"}], correctAnswer:"B", explanation:"YOLO processa imagem em uma única passagem (real-time), R-CNN requer múltiplos estágios." },
  { id:"ia_rl_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Aprendizado por reforço", difficulty:"médio", statement:"No aprendizado por reforço, Q-learning atualiza Q(s,a) baseado em:", alternatives:[{letter:"A",text:"Apenas na recompensa imediata"},{letter:"B",text:"Recompensa imediata + valor futuro descontado (Bellman)"},{letter:"C",text:"Apenas no estado anterior"},{letter:"D",text:"Na média de todas as recompensas"},{letter:"E",text:"No número de estados visitados"}], correctAnswer:"B", explanation:"Q(s,a) ← Q(s,a) + α[r + γ max Q(s',a') - Q(s,a)] (equação de Bellman)." },
  { id:"ia_metricas_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Métricas de avaliação", difficulty:"médio", statement:"Classificador com Precision=0,9 e Recall=0,3. Qual a situação?", alternatives:[{letter:"A",text:"Excelente desempenho geral"},{letter:"B",text:"Alta precisão mas perde muitos positivos (recall baixo)"},{letter:"C",text:"Baixa precisão"},{letter:"D",text:"Perfeito equilíbrio"},{letter:"E",text:"Não é possível calcular F1"}], correctAnswer:"B", explanation:"Precision alta: quando prevê positivo, geralmente acerta. Recall baixo: perde muitos positivos reais." },
  { id:"ia_etica_ia_001", topic:"Inteligência Artificial", macroarea:"Segurança/IA", element:"Ética em IA", difficulty:"médio", statement:"Viés algorítmico em IA ocorre quando:", alternatives:[{letter:"A",text:"O algoritmo é muito lento"},{letter:"B",text:"O modelo reproduz e amplifica preconceitos dos dados de treino"},{letter:"C",text:"O algoritmo é muito preciso"},{letter:"D",text:"Não há dados suficientes"},{letter:"E",text:"O modelo é underfitting"}], correctAnswer:"B", explanation:"Viés algorítmico: dados tendenciosos → modelo discriminatório. Ex: recrutamento com dados históricos enviesados." },

  // ===== CIÊNCIA DE DADOS (10) =====
  { id:"cd_crval_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"CRISP-DM", difficulty:"fácil", statement:"Qual é a primeira fase do metodologia CRISP-DM?", alternatives:[{letter:"A",text:"Preparação dos dados"},{letter:"B",text:"Entendimento do negócio"},{letter:"C",text:"Modelagem"},{letter:"D",text:"Avaliação"},{letter:"E",text:"Implantação"}], correctAnswer:"B", explanation:"CRISP-DM: 1) Entendimento do negócio → 2) Entendimento dos dados → 3) Preparação → 4) Modelagem → 5) Avaliação → 6) Implantação." },
  { id:"cd_eda_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"EDA", difficulty:"médio", statement:"Na Análise Exploratória de Dados (EDA), qual técnica NÃO é comum?", alternatives:[{letter:"A",text:"Histogramas e boxplots"},{letter:"B",text:"Correlação entre variáveis"},{letter:"C",text:"Treinamento de modelo preditivo"},{letter:"D",text:"Detecção de outliers"},{letter:"E",text:"Distribuição de frequências"}], correctAnswer:"C", explanation:"EDA explora dados (visualização, estatísticas). Treinamento de modelo é fase posterior (modelagem)." },
  { id:"cd_sql_analise_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"SQL para análise", difficulty:"médio", statement:"Qual cláusula SQL é usada para calcular médias agrupadas?", alternatives:[{letter:"A",text:"ORDER BY"},{letter:"B",text:"GROUP BY com AVG()"},{letter:"C",text:"HAVING com SUM()"},{letter:"D",text:"WHERE com COUNT()"},{letter:"E",text:"DISTINCT"}], correctAnswer:"B", explanation:"GROUP BY + funções agregadas (AVG, SUM, COUNT) calculam estatísticas por grupo." },
  { id:"cd_visualizacao_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"Visualização", difficulty:"fácil", statement:"Para comparar proporções de categorias, qual gráfico é mais adequado?", alternatives:[{letter:"A",text:"Linha"},{letter:"B",text:"Pizza (pie chart) ou barras de proporção"},{letter:"C",text:"Scatter plot"},{letter:"D",text:"Histograma"},{letter:"E",text:"Boxplot"}], correctAnswer:"B", explanation:"Gráficos de pizza ou barras proporcionais são ideais para comparar partes de um todo." },
  { id:"cd_limpeza_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"Limpeza de dados", difficulty:"médio", statement:"Técnica adequada para tratar valores ausentes (missing values) numéricos?", alternatives:[{letter:"A",text:"Sempre remover as linhas"},{letter:"B",text:"Imputação pela média/mediana ou modelos preditivos"},{letter:"C",text:"Ignorar missing values"},{letter:"D",text:"Substituir por texto"},{letter:"E",text:"Deletar a coluna inteira"}], correctAnswer:"B", explanation:"Imputação (média, mediana, KNN, regressão) preserva dados enquanto trata ausências." },
  { id:"cd_regression_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"Regressão linear", difficulty:"médio", statement:"R² (R-quadrado) próximo de 0 indica:", alternatives:[{letter:"A",text:"Modelo perfeito"},{letter:"B",text:"Modelo não explica a variância dos dados"},{letter:"C",text:"Overfitting"},{letter:"D",text:"Dados ausentes"},{letter:"E",text:"Underfitting"}], correctAnswer:"B", explanation:"R²=0: modelo não explica variância. R²=1: ajuste perfeito." },
  { id:"cd_pandas_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"Ferramentas (Pandas)", difficulty:"fácil", statement:"Em Pandas, qual método remove duplicatas de um DataFrame?", alternatives:[{letter:"A",text:"df.merge()"},{letter:"B",text:"df.drop_duplicates()"},{letter:"C",text:"df.sort_values()"},{letter:"D",text:"df.fillna()"},{letter:"E",text:"df.groupby()"}], correctAnswer:"B", explanation:"drop_duplicates() remove linhas duplicadas de um DataFrame." },
  { id:"cd_bigdata_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"Big Data", difficulty:"médio", statement:"Os 5 V's do Big Data incluem Volume, Velocidade, Variedade, Veracidade e:", alternatives:[{letter:"A",text:"Visualização"},{letter:"B",text:"Valor"},{letter:"C",text:"Versão"},{letter:"D",text:"Virtualização"},{letter:"E",text:"Validação"}], correctAnswer:"B", explanation:"5 V's: Volume, Velocidade, Variedade, Veracidade, Valor." },
  { id:"cd_normalizacao_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"Normalização de dados", difficulty:"médio", statement:"Por que normalizar features antes de treinar modelos sensíveis à distância (KNN, SVM)?", alternatives:[{letter:"A",text:"Para aumentar o tempo de treinamento"},{letter:"B",text:"Para evitar que features com escalas maiores dominem o cálculo de distância"},{letter:"C",text:"Para adicionar bias ao modelo"},{letter:"D",text:"Para reduzir a precisão"},{letter:"E",text:"Não é necessário"}], correctAnswer:"B", explanation:"Normalização (z-score, min-max) coloca features na mesma escala, evitando dominação." },
  { id:"cd_etica_001", topic:"Ciência de Dados", macroarea:"Segurança/IA", element:"Ética em dados", difficulty:"médio", statement:"Princípio do LGPD que exige que o titular dos dados seja informado sobre o tratamento:", alternatives:[{letter:"A",text:"Anonimização"},{letter:"B",text:"Transparência"},{letter:"C",text:"Portabilidade"},{letter:"D",text:"Eliminação"},{letter:"E",text:"Consentimento"}], correctAnswer:"B", explanation:"LGPD: Transparência = titular tem direito de saber como seus dados são tratados." },

  // ===== ÉTICA PROFISSIONAL (5) =====
  { id:"eti_codigo_001", topic:"Ética Profissional", macroarea:"Segurança/IA", element:"Código de ética", difficulty:"fácil", statement:"Qual princípio ético é fundamental para profissionais de TI?", alternatives:[{letter:"A",text:"Maximizar lucro a qualquer custo"},{letter:"B",text:"Atuar com integridade, competência e responsabilidade social"},{letter:"C",text:"Compartilhar senhas quando solicitado"},{letter:"D",text:"Copiar software livremente"},{letter:"E",text:"Ignorar vulnerabilidades encontradas"}], correctAnswer:"B", explanation:"Códigos de ética (CFP, ACM, IEEE) enfatizam integridade, competência e responsabilidade social." },
  { id:"eti_lgpd_001", topic:"Ética Profissional", macroarea:"Segurança/IA", element:"LGPD", difficulty:"médio", statement:"Na LGPD, qual NÃO é uma base legal para tratamento de dados pessoais?", alternatives:[{letter:"A",text:"Consentimento do titular"},{letter:"B",text:"Execução de contrato"},{letter:"C",text:"Curiosidade do administrador do sistema"},{letter:"D",text:"Legítimo interesse"},{letter:"E",text:"Obrigação legal"}], correctAnswer:"C", explanation:"LGPD exige bases legais específicas (consentimento, contrato, legítimo interesse, etc.). Curiosidade não é base legal." },
  { id:"eti_privacidade_001", topic:"Ética Profissional", macroarea:"Segurança/IA", element:"Privacidade", difficulty:"médio", statement:"Princípio de Privacy by Design significa:", alternatives:[{letter:"A",text:"Adicionar privacidade após o desenvolvimento"},{letter:"B",text:"Incorporar privacidade desde o início do design do sistema"},{letter:"C",text:"Não coletar dados pessoais"},{letter:"D",text:"Usar apenas senhas"},{letter:"E",text:"Ignorar regulamentações"}], correctAnswer:"B", explanation:"Privacy by Design = privacidade como requisito desde a concepção, não como adição posterior." },
  { id:"eti_propriedade_001", topic:"Ética Profissional", macroarea:"Segurança/IA", element:"Propriedade intelectual", difficulty:"médio", statement:"Sobre software livre (open source), qual afirmação está correta?", alternatives:[{letter:"A",text:"Pode ser copiado livremente sem nenhuma restrição"},{letter:"B",text:"Licenças como GPL, MIT e Apache definem termos de uso, modificação e distribuição"},{letter:"C",text:"Software livre é sempre de baixa qualidade"},{letter:"D",text:"Não é possível comercializar software livre"},{letter:"E",text:"Software livre não tem direitos autorais"}], correctAnswer:"B", explanation:"Cada licença open source tem suas próprias condições (copyleft, permissiva, etc.)." },
  { id:"eti_responsabilidade_001", topic:"Ética Profissional", macroarea:"Segurança/IA", element:"Responsabilidade social", difficulty:"médio", statement:"Profissional de TI que descobre vulnerabilidade crítica em sistema de saúde. O que é eticamente correto?", alternatives:[{letter:"A",text:"Explorar a vulnerabilidade"},{letter:"B",text:"Vender a informação"},{letter:"C",text:"Reportar responsavelmente à organização antes da divulgação pública"},{letter:"D",text:"Ignorar e continuar"},{letter:"E",text:"Publicar imediatamente sem aviso"}], correctAnswer:"C", explanation:"Responsible disclosure: reportar à organização primeiro, dando tempo para correção antes da divulgação." },

  // ===== LEGISLAÇÃO (5) =====
  { id:"leg_lgpd_001", topic:"Legislação", macroarea:"Segurança/IA", element:"LGPD - direitos", difficulty:"médio", statement:"Qual direito do titular NÃO é garantido pela LGPD?", alternatives:[{letter:"A",text:"Confirmação de existência de tratamento"},{letter:"B",text:"Acesso aos dados"},{letter:"C",text:"Exclusão dos dados (esquecimento)"},{letter:"D",text:"Hackear o sistema da empresa para verificar dados"},{letter:"E",text:"Portabilidade dos dados"}], correctAnswer:"D", explanation:"LGPD garante acesso, correção, exclusão, portabilidade. Hacking é crime independentemente da LGPD." },
  { id:"leg_carlos_001", topic:"Legislação", macroarea:"Segurança/IA", element:"Marco Civil da Internet", difficulty:"fácil", statement:"O Marco Civil da Internet (Lei 12.965/2014) estabelece, entre outros:", alternatives:[{letter:"A",text:"Censura prévia de conteúdo"},{letter:"B",text:"Princípios de neutralidade de rede, privacidade e liberdade de expressão"},{letter:"C",text:"Monitoramento obrigatório de emails"},{letter:"D",text:"Proibição de redes sociais"},{letter:"E",text:"Eliminação de Wi-Fi público"}], correctAnswer:"B", explanation:"Marco Civil: neutralidade de rede, proteção de dados, liberdade de expressão, conservação de logs." },
  { id:"leg_crimes_001", topic:"Legislação", macroarea:"Segurança/IA", element:"Crimes digitais", difficulty:"médio", statement:"Lei 12.737/2012 (Lei Carolina Dieckmann) tipifica o crime de:", alternatives:[{letter:"A",text:"Invasão de dispositivo informático (hacking)"},{letter:"B",text:"Estacionamento irregular"},{letter:"C",text:"Roubo de banco"},{letter:"D",text:"Descumprimento de contrato"},{letter:"E",text:"Calúnia oral"}], correctAnswer:"A", explanation:"Lei Carolina Dieckmann criminaliza invasão de dispositivos informáticos com pena de 3 meses a 1 ano." },
  { id:"leg_economia_001", topic:"Legislação", macroarea:"Segurança/IA", element:"Economia digital", difficulty:"médio", statement:"Sobre a validade jurídica de documentos eletrônicos no Brasil:", alternatives:[{letter:"A",text:"Documentos eletrônicos não têm validade"},{letter:"B",text:"Documento eletrônico com ICP-Brasil (assinatura digital) tem mesma validade que documento físico"},{letter:"C",text:"Apenas documentos impressos são válidos"},{letter:"D",text:"Emails nunca podem servir como prova"},{letter:"E",text:"Contratos eletrônicos são ilegais"}], correctAnswer:"B", explanation:"Infraestrutura de Chaves Públicas Brasileira (ICP-Brasil) garante validade jurídica a documentos eletrônicos." },
  { id:"leg_software_001", topic:"Legislação", macroarea:"Segurança/IA", element:"Lei de Software", difficulty:"fácil", statement:"A Lei de Software (Lei 9.609/1998) protege:", alternatives:[{letter:"A",text:"Apenas hardware"},{letter:"B",text:"Direitos autorais de programas de computador e sua comercialização"},{letter:"C",text:"Apenas marcas"},{letter:"D",text:"Apenas patentes"},{letter:"E",text:"Nada relacionado a TI"}], correctAnswer:"B", explanation:"Lei 9.609/1998 protege direitos autorais de software, regula comercialização e propriedade intelectual." },
];

async function main() {
  console.log('🌱 Iniciando seed de questões e simulados...\n');

  // Get microareas
  const microareas = await prisma.microarea.findMany({ include: { elements: true } });
  console.log(`📍 Microareas encontradas: ${microareas.length}`);

  const allQuestions = [...batch1, ...batch2, ...batch3];
  console.log(`📝 Total de questões para seed: ${allQuestions.length}`);

  let seeded = 0;
  let errors = 0;

  for (const q of allQuestions) {
    try {
      const code = TOPIC_TO_CODE[q.topic];
      if (!code) { errors++; continue; }

      const microarea = microareas.find(m => m.code === code);
      if (!microarea) { errors++; continue; }

      const tri = getTRI(q.difficulty);

      await prisma.question.create({
        data: {
          code: q.id,
          type: 'OBJETIVA',
          statement: q.statement,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation,
          difficulty: q.difficulty,
          triA: tri.a,
          triB: tri.b,
          triC: tri.c,
          triCalibrated: false,
          source: 'elaborada',
          microareaId: microarea.id,
          elementId: microarea.elements[0]?.id || null,
          status: 'APROVADA',
          alternatives: {
            create: q.alternatives.map(a => ({ letter: a.letter, text: a.text }))
          }
        }
      });
      seeded++;
    } catch (e: any) {
      errors++;
      if (errors <= 3) console.log(`❌ Erro em ${q.id}: ${e.message?.substring(0, 80)}`);
    }
  }

  console.log(`\n✅ Questões seedadas: ${seeded}`);
  if (errors > 0) console.log(`❌ Erros: ${errors}`);

  // Create Simulados
  const allQ = await prisma.question.findMany({ select: { id: true } });
  console.log(`\n📊 Questões no banco: ${allQ.length}`);

  const simuladoConfigs = [
    { title: 'Simulado Diagnóstico Geral', type: 'DIAGNOSTICO', phase: 1, timeLimit: 120, desc: 'Avaliação diagnóstica com questões de todas as microáreas para identificar pontos fortes e fracos.', qCount: 20 },
    { title: 'Simulado ENADE Completo', type: 'ENADE_SIMULADO', phase: 3, timeLimit: 240, desc: 'Simulação completa do ENADE com 40 questões no formato oficial.', qCount: Math.min(40, allQ.length) },
    { title: 'Simulado Macroarea Desenvolvimento', type: 'MACROAREA', phase: 2, timeLimit: 90, desc: 'Focado em BD, Eng. Software, SO, Redes e Sistemas Distribuídos.', qCount: 20 },
    { title: 'Simulado Fundamentos & Teoria', type: 'MACROAREA', phase: 1, timeLimit: 90, desc: 'Focado em Lógica, Matemática Discreta, Autômatos e Algoritmos.', qCount: 20 },
    { title: 'Simulado Segurança e IA', type: 'MACROAREA', phase: 2, timeLimit: 90, desc: 'Focado em Criptografia, IA, Ciência de Dados, Ética e Legislação.', qCount: 20 },
  ];

  for (const cfg of simuladoConfigs) {
    const shuffled = [...allQ].sort(() => Math.random() - 0.5);
    const selected = shuffled.slice(0, cfg.qCount);
    await prisma.simulado.create({
      data: {
        title: cfg.title,
        description: cfg.desc,
        type: cfg.type,
        phase: cfg.phase,
        timeLimit: cfg.timeLimit,
        questionCount: selected.length,
        active: true,
        configs: { create: selected.map((q, i) => ({ questionId: q.id, order: i })) }
      }
    });
    console.log(`🎯 Criado: ${cfg.title} (${selected.length} questões)`);
  }

  const finalQ = await prisma.question.count();
  const finalS = await prisma.simulado.count();
  console.log(`\n🎉 Final: ${finalQ} questões, ${finalS} simulados`);

  await prisma.$disconnect();
}

main().catch(e => { console.error(e); process.exit(1); });
